//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swift.Net.Mt.Category5
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// MT505 (SRG 2019)
    /// <summary>
    public partial class MT505 : SwiftMessage
    {
        
		public override SwiftBlock4 Block4 { get => new SwiftBlock4(GetBlock4Tags()); set => SetBlock4Tags(value); }

        /// <summary>
        /// General Information
        /// <summary>
		public MT505_SequenceA SequenceA { get; set; }
        /// <summary>
        /// Sequence B Collateral Details
        /// <summary>
		public List<MT505_SequenceB> SequenceBList { get; set; }
        /// <summary>
        /// Sequence C Settlement Details
        /// <summary>
		public MT505_SequenceC SequenceC { get; set; }
        /// <summary>
        /// Sequence D Cash Settlement Details
        /// <summary>
		public MT505_SequenceD SequenceD { get; set; }
        /// <summary>
        /// Additional Information
        /// <summary>
		public MT505_SequenceE SequenceE { get; set; }
        
        public MT505()
        {
        }
        
        public MT505(SwiftTagList tags)
        {
			SetBlock4Tags(tags);
        }
        
        public virtual SwiftTagList GetBlock4Tags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (SequenceA != null)
				tags.AddRange(SequenceA.GetTags());
			if (SequenceBList != null)
				tags.AddRange(SequenceBList.SelectMany(x => x.GetTags()).ToList());
			if (SequenceC != null)
				tags.AddRange(SequenceC.GetTags());
			if (SequenceD != null)
				tags.AddRange(SequenceD.GetTags());
			if (SequenceE != null)
				tags.AddRange(SequenceE.GetTags());
			return tags;
        }
        
        public virtual void SetBlock4Tags(SwiftTagList tags)
        {
			SequenceA = MT505_SequenceA.GetMT505_SequenceA(tags);
			SequenceBList = MT505_SequenceB.GetMT505_SequenceBList(tags);
			SequenceC = MT505_SequenceC.GetMT505_SequenceC(tags);
			SequenceD = MT505_SequenceD.GetMT505_SequenceD(tags);
			SequenceE = MT505_SequenceE.GetMT505_SequenceE(tags);
        }
        
        public static MT505 Parse(string message)
        {
			SwiftMessage swiftMessage = new SwiftParser().GetSwiftMessage(message);
			MT505 result = new MT505()
			{
				Block1 = swiftMessage.Block1,
				Block2 = swiftMessage.Block2,
				Block3 = swiftMessage.Block3,
				Block4 = swiftMessage.Block4,
				Block5 = swiftMessage.Block5,
			};
			return result;
        }
        
        public static string Write(MT505 message)
        {
			return new SwiftWriter().GetFinMessage(message);
        }
    }
    
    /// <summary>
    /// General Information
    /// <summary>
    public partial class MT505_SequenceA
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "GENL";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public List<string> Tag20C_Reference { get; set; }
        /// <summary>
        /// Function Of The Message
        /// <summary>
		public string Tag23G_FunctionOfTheMessage { get; set; }
        /// <summary>
        /// Agreement
        /// <summary>
		public List<MT505_SequenceA1> SequenceA1List { get; set; }
        /// <summary>
        /// Preparation Date Time
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Preparation Date Time
        /// <summary>
		public string Tag98C_Date { get; set; }
        /// <summary>
        /// Trade Date/Time
        /// <summary>
		public string Tag98E_DateTime { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22H_Indicator { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party Contact Narrative
        /// <summary>
		public string Tag70C_Narrative { get; set; }
        /// <summary>
        /// SubSequence A2 Linkages
        /// <summary>
		public List<MT505_SequenceA2> SequenceA2List { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "GENL";
        /// <summary>
        /// End Of  Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceA()
        {
        }
        
        public MT505_SequenceA(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag20C_Reference != null)
				tags.AddRange(Tag20C_Reference.Select(x => new SwiftTag("20C", x)).ToList());
			if (Tag23G_FunctionOfTheMessage != null)
				tags.Add(new SwiftTag("23G", Tag23G_FunctionOfTheMessage));
			if (SequenceA1List != null)
				tags.AddRange(SequenceA1List.SelectMany(x => x.GetTags()).ToList());
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98C_Date != null)
				tags.Add(new SwiftTag("98C", Tag98C_Date));
			if (Tag98E_DateTime != null)
				tags.Add(new SwiftTag("98E", Tag98E_DateTime));
			if (Tag22H_Indicator != null)
				tags.AddRange(Tag22H_Indicator.Select(x => new SwiftTag("22H", x)).ToList());
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag70C_Narrative != null)
				tags.Add(new SwiftTag("70C", Tag70C_Narrative));
			if (SequenceA2List != null)
				tags.AddRange(SequenceA2List.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "20C") && (i <= 2))
				{
					if (Tag20C_Reference == null)
						Tag20C_Reference = new List<string>();
					Tag20C_Reference.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "23G") && (i <= 3))
				{
					Tag23G_FunctionOfTheMessage = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "98A") && (i <= 4))
				{
					Tag98A_Date = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "98C") && (i <= 4))
				{
					Tag98C_Date = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "98E") && (i <= 4))
				{
					Tag98E_DateTime = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "22H") && (i <= 5))
				{
					if (Tag22H_Indicator == null)
						Tag22H_Indicator = new List<string>();
					Tag22H_Indicator.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "22F") && (i <= 5))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "95P") && (i <= 6))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "95Q") && (i <= 6))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "95R") && (i <= 6))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "70C") && (i <= 7))
				{
					Tag70C_Narrative = tag.Value;
					i = 7;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 8))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 8;
				}
			}
			SequenceA1List = MT505_SequenceA1.GetMT505_SequenceA1List(tags);
			SequenceA2List = MT505_SequenceA2.GetMT505_SequenceA2List(tags);
        }
        
        public static MT505_SequenceA GetMT505_SequenceA(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT505_SequenceA.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceA.Tag16S_EndOfBlock_Value));
			return new MT505_SequenceA(subBlock);
        }
    }
    
    /// <summary>
    /// Agreement
    /// <summary>
    public partial class MT505_SequenceA1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "AGRE";
        /// <summary>
        /// Start Of  Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Agreement Indicator
        /// <summary>
		public string Tag22F_Indicator { get; set; }
        /// <summary>
        /// Agreement Date
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Agreement Version Number
        /// <summary>
		public string Tag13B_Number { get; set; }
        /// <summary>
        /// Agreement Narrative
        /// <summary>
		public string Tag70C_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "AGRE";
        /// <summary>
        /// End Of  Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceA1()
        {
        }
        
        public MT505_SequenceA1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag22F_Indicator != null)
				tags.Add(new SwiftTag("22F", Tag22F_Indicator));
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag13B_Number != null)
				tags.Add(new SwiftTag("13B", Tag13B_Number));
			if (Tag70C_Narrative != null)
				tags.Add(new SwiftTag("70C", Tag70C_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "22F") && (i <= 2))
				{
					Tag22F_Indicator = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "98A") && (i <= 3))
				{
					Tag98A_Date = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "13B") && (i <= 4))
				{
					Tag13B_Number = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "70C") && (i <= 5))
				{
					Tag70C_Narrative = tag.Value;
					i = 5;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 6))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 6;
				}
			}
        }
        
        public static List<MT505_SequenceA1> GetMT505_SequenceA1List(SwiftTagList tags)
        {
			List<MT505_SequenceA1> result = new List<MT505_SequenceA1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT505_SequenceA1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceA1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT505_SequenceA1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceA1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT505_SequenceA1 sequence = new MT505_SequenceA1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// SubSequence A2 Linkages
    /// <summary>
    public partial class MT505_SequenceA2
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "LINK";
        /// <summary>
        /// Start Of  Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Linked Message
        /// <summary>
		public string Tag13A_NumberIdentification { get; set; }
        /// <summary>
        /// Linked Message
        /// <summary>
		public string Tag13B_NumberIdentification { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "LINK";
        /// <summary>
        /// End Of  Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceA2()
        {
        }
        
        public MT505_SequenceA2(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag13A_NumberIdentification != null)
				tags.Add(new SwiftTag("13A", Tag13A_NumberIdentification));
			if (Tag13B_NumberIdentification != null)
				tags.Add(new SwiftTag("13B", Tag13B_NumberIdentification));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "13A") && (i <= 2))
				{
					Tag13A_NumberIdentification = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "13B") && (i <= 2))
				{
					Tag13B_NumberIdentification = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "20C") && (i <= 3))
				{
					Tag20C_Reference = tag.Value;
					i = 3;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 4))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 4;
				}
			}
        }
        
        public static List<MT505_SequenceA2> GetMT505_SequenceA2List(SwiftTagList tags)
        {
			List<MT505_SequenceA2> result = new List<MT505_SequenceA2>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT505_SequenceA2.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceA2.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT505_SequenceA2.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceA2.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT505_SequenceA2 sequence = new MT505_SequenceA2(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Sequence B Collateral Details
    /// <summary>
    public partial class MT505_SequenceB
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "COLD";
        /// <summary>
        /// Start Of  Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Collateral Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22H_Indicator { get; set; }
        /// <summary>
        /// Settlement Date
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Subsequence B1 Security Collateral Details
        /// <summary>
		public MT505_SequenceB1 SequenceB1 { get; set; }
        /// <summary>
        /// Subsequence B2 Cash Collateral Details
        /// <summary>
		public MT505_SequenceB2 SequenceB2 { get; set; }
        /// <summary>
        /// Subsequence B3 Other Collateral Details
        /// <summary>
		public MT505_SequenceB3 SequenceB3 { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "COLD";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceB()
        {
        }
        
        public MT505_SequenceB(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (Tag22H_Indicator != null)
				tags.AddRange(Tag22H_Indicator.Select(x => new SwiftTag("22H", x)).ToList());
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (SequenceB1 != null)
				tags.AddRange(SequenceB1.GetTags());
			if (SequenceB2 != null)
				tags.AddRange(SequenceB2.GetTags());
			if (SequenceB3 != null)
				tags.AddRange(SequenceB3.GetTags());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "20C") && (i <= 2))
				{
					Tag20C_Reference = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "22F") && (i <= 3))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "22H") && (i <= 3))
				{
					if (Tag22H_Indicator == null)
						Tag22H_Indicator = new List<string>();
					Tag22H_Indicator.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "98A") && (i <= 4))
				{
					Tag98A_Date = tag.Value;
					i = 4;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 5))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 5;
				}
			}
			SequenceB1 = MT505_SequenceB1.GetMT505_SequenceB1(tags);
			SequenceB2 = MT505_SequenceB2.GetMT505_SequenceB2(tags);
			SequenceB3 = MT505_SequenceB3.GetMT505_SequenceB3(tags);
        }
        
        public static List<MT505_SequenceB> GetMT505_SequenceBList(SwiftTagList tags)
        {
			List<MT505_SequenceB> result = new List<MT505_SequenceB>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT505_SequenceB.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceB.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT505_SequenceB.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceB.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT505_SequenceB sequence = new MT505_SequenceB(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Subsequence B1 Security Collateral Details
    /// <summary>
    public partial class MT505_SequenceB1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "SCOL";
        /// <summary>
        /// Start Of  Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Identification Of Financial Instrument
        /// <summary>
		public string Tag35B_IdentificationOfFinancialInstrument { get; set; }
        /// <summary>
        /// Quantity Of Securities Collateral
        /// <summary>
		public string Tag36B_QuantityOfFinancialInstrument { get; set; }
        /// <summary>
        /// Ownership Flag
        /// <summary>
		public string Tag17B_Flag { get; set; }
        /// <summary>
        /// SubSequence B1a SettlementDetails
        /// <summary>
		public MT505_SequenceB1a SequenceB1a { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "SCOL";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceB1()
        {
        }
        
        public MT505_SequenceB1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag35B_IdentificationOfFinancialInstrument != null)
				tags.Add(new SwiftTag("35B", Tag35B_IdentificationOfFinancialInstrument));
			if (Tag36B_QuantityOfFinancialInstrument != null)
				tags.Add(new SwiftTag("36B", Tag36B_QuantityOfFinancialInstrument));
			if (Tag17B_Flag != null)
				tags.Add(new SwiftTag("17B", Tag17B_Flag));
			if (SequenceB1a != null)
				tags.AddRange(SequenceB1a.GetTags());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "35B") && (i <= 2))
				{
					Tag35B_IdentificationOfFinancialInstrument = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "36B") && (i <= 3))
				{
					Tag36B_QuantityOfFinancialInstrument = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "17B") && (i <= 4))
				{
					Tag17B_Flag = tag.Value;
					i = 4;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 5))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 5;
				}
			}
			SequenceB1a = MT505_SequenceB1a.GetMT505_SequenceB1a(tags);
        }
        
        public static MT505_SequenceB1 GetMT505_SequenceB1(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT505_SequenceB1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceB1.Tag16S_EndOfBlock_Value));
			return new MT505_SequenceB1(subBlock);
        }
    }
    
    /// <summary>
    /// SubSequence B1a SettlementDetails
    /// <summary>
    public partial class MT505_SequenceB1a
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "SETDET";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22H_Indicator { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Subsequence B1a1 SettlementParties
        /// <summary>
		public List<MT505_SequenceB1a1> SequenceB1a1List { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "SETDET";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceB1a()
        {
        }
        
        public MT505_SequenceB1a(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag22H_Indicator != null)
				tags.AddRange(Tag22H_Indicator.Select(x => new SwiftTag("22H", x)).ToList());
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (SequenceB1a1List != null)
				tags.AddRange(SequenceB1a1List.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "22H") && (i <= 2))
				{
					if (Tag22H_Indicator == null)
						Tag22H_Indicator = new List<string>();
					Tag22H_Indicator.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "22F") && (i <= 2))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 2;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 3))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 3;
				}
			}
			SequenceB1a1List = MT505_SequenceB1a1.GetMT505_SequenceB1a1List(tags);
        }
        
        public static MT505_SequenceB1a GetMT505_SequenceB1a(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT505_SequenceB1a.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceB1a.Tag16S_EndOfBlock_Value));
			return new MT505_SequenceB1a(subBlock);
        }
    }
    
    /// <summary>
    /// Subsequence B1a1 SettlementParties
    /// <summary>
    public partial class MT505_SequenceB1a1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "SETPRTY";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95C_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95S_Party { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public string Tag97A_Account { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public string Tag97B_Account { get; set; }
        /// <summary>
        /// Party Contract Narrative
        /// <summary>
		public string Tag70C_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "SETPRTY";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceB1a1()
        {
        }
        
        public MT505_SequenceB1a1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95C_Party != null)
				tags.AddRange(Tag95C_Party.Select(x => new SwiftTag("95C", x)).ToList());
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95S_Party != null)
				tags.AddRange(Tag95S_Party.Select(x => new SwiftTag("95S", x)).ToList());
			if (Tag97A_Account != null)
				tags.Add(new SwiftTag("97A", Tag97A_Account));
			if (Tag97B_Account != null)
				tags.Add(new SwiftTag("97B", Tag97B_Account));
			if (Tag70C_Narrative != null)
				tags.Add(new SwiftTag("70C", Tag70C_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95C") && (i <= 2))
				{
					if (Tag95C_Party == null)
						Tag95C_Party = new List<string>();
					Tag95C_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95S") && (i <= 2))
				{
					if (Tag95S_Party == null)
						Tag95S_Party = new List<string>();
					Tag95S_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "97A") && (i <= 3))
				{
					Tag97A_Account = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "97B") && (i <= 3))
				{
					Tag97B_Account = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "70C") && (i <= 4))
				{
					Tag70C_Narrative = tag.Value;
					i = 4;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 5))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 5;
				}
			}
        }
        
        public static List<MT505_SequenceB1a1> GetMT505_SequenceB1a1List(SwiftTagList tags)
        {
			List<MT505_SequenceB1a1> result = new List<MT505_SequenceB1a1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT505_SequenceB1a1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceB1a1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT505_SequenceB1a1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceB1a1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT505_SequenceB1a1 sequence = new MT505_SequenceB1a1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Subsequence B2 Cash Collateral Details
    /// <summary>
    public partial class MT505_SequenceB2
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "CCOL";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Deposit Amount
        /// <summary>
		public string Tag19B_Amount { get; set; }
        /// <summary>
        /// Type Of Deposit Indicator
        /// <summary>
		public string Tag22H_Indicator { get; set; }
        /// <summary>
        /// Maturity Date
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// SubSequence B2 Cash Settlement Details
        /// <summary>
		public MT505_SequenceB2a SequenceB2a { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "CCOL";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceB2()
        {
        }
        
        public MT505_SequenceB2(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag19B_Amount != null)
				tags.Add(new SwiftTag("19B", Tag19B_Amount));
			if (Tag22H_Indicator != null)
				tags.Add(new SwiftTag("22H", Tag22H_Indicator));
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (SequenceB2a != null)
				tags.AddRange(SequenceB2a.GetTags());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "19B") && (i <= 2))
				{
					Tag19B_Amount = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "22H") && (i <= 3))
				{
					Tag22H_Indicator = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "98A") && (i <= 4))
				{
					Tag98A_Date = tag.Value;
					i = 4;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 5))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 5;
				}
			}
			SequenceB2a = MT505_SequenceB2a.GetMT505_SequenceB2a(tags);
        }
        
        public static MT505_SequenceB2 GetMT505_SequenceB2(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT505_SequenceB2.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceB2.Tag16S_EndOfBlock_Value));
			return new MT505_SequenceB2(subBlock);
        }
    }
    
    /// <summary>
    /// SubSequence B2 Cash Settlement Details
    /// <summary>
    public partial class MT505_SequenceB2a
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "CASHSET";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Settlement Transaction Condition
        /// <summary>
		public string Tag22F_Indicator { get; set; }
        /// <summary>
        /// SubSequence B2a1 Cash Settlement Details
        /// <summary>
		public List<MT505_SequenceB2a1> SequenceB2a1List { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "CASHSET";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceB2a()
        {
        }
        
        public MT505_SequenceB2a(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag22F_Indicator != null)
				tags.Add(new SwiftTag("22F", Tag22F_Indicator));
			if (SequenceB2a1List != null)
				tags.AddRange(SequenceB2a1List.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "22F") && (i <= 2))
				{
					Tag22F_Indicator = tag.Value;
					i = 2;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 3))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 3;
				}
			}
			SequenceB2a1List = MT505_SequenceB2a1.GetMT505_SequenceB2a1List(tags);
        }
        
        public static MT505_SequenceB2a GetMT505_SequenceB2a(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT505_SequenceB2a.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceB2a.Tag16S_EndOfBlock_Value));
			return new MT505_SequenceB2a(subBlock);
        }
    }
    
    /// <summary>
    /// SubSequence B2a1 Cash Settlement Details
    /// <summary>
    public partial class MT505_SequenceB2a1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "CSHPRTY";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95S_Party { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97A_Account { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97E_Account { get; set; }
        /// <summary>
        /// Party Contract Narrative
        /// <summary>
		public string Tag70C_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "CSHPRTY";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceB2a1()
        {
        }
        
        public MT505_SequenceB2a1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95S_Party != null)
				tags.AddRange(Tag95S_Party.Select(x => new SwiftTag("95S", x)).ToList());
			if (Tag97A_Account != null)
				tags.AddRange(Tag97A_Account.Select(x => new SwiftTag("97A", x)).ToList());
			if (Tag97E_Account != null)
				tags.AddRange(Tag97E_Account.Select(x => new SwiftTag("97E", x)).ToList());
			if (Tag70C_Narrative != null)
				tags.Add(new SwiftTag("70C", Tag70C_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95S") && (i <= 2))
				{
					if (Tag95S_Party == null)
						Tag95S_Party = new List<string>();
					Tag95S_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "97A") && (i <= 3))
				{
					if (Tag97A_Account == null)
						Tag97A_Account = new List<string>();
					Tag97A_Account.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "97E") && (i <= 3))
				{
					if (Tag97E_Account == null)
						Tag97E_Account = new List<string>();
					Tag97E_Account.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "70C") && (i <= 4))
				{
					Tag70C_Narrative = tag.Value;
					i = 4;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 5))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 5;
				}
			}
        }
        
        public static List<MT505_SequenceB2a1> GetMT505_SequenceB2a1List(SwiftTagList tags)
        {
			List<MT505_SequenceB2a1> result = new List<MT505_SequenceB2a1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT505_SequenceB2a1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceB2a1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT505_SequenceB2a1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceB2a1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT505_SequenceB2a1 sequence = new MT505_SequenceB2a1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Subsequence B3 Other Collateral Details
    /// <summary>
    public partial class MT505_SequenceB3
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "BCOL";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Type Of Other Collateral Indicators
        /// <summary>
		public string Tag22H_Indicator { get; set; }
        /// <summary>
        /// Date 
        /// <summary>
		public List<string> Tag98A_Date { get; set; }
        /// <summary>
        /// Date Code
        /// <summary>
		public List<string> Tag98B_DateCode { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public string Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public string Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public string Tag95R_Party { get; set; }
        /// <summary>
        /// Deposit Amount
        /// <summary>
		public string Tag19B_Amount { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "BCOL";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceB3()
        {
        }
        
        public MT505_SequenceB3(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag22H_Indicator != null)
				tags.Add(new SwiftTag("22H", Tag22H_Indicator));
			if (Tag98A_Date != null)
				tags.AddRange(Tag98A_Date.Select(x => new SwiftTag("98A", x)).ToList());
			if (Tag98B_DateCode != null)
				tags.AddRange(Tag98B_DateCode.Select(x => new SwiftTag("98B", x)).ToList());
			if (Tag95P_Party != null)
				tags.Add(new SwiftTag("95P", Tag95P_Party));
			if (Tag95Q_Party != null)
				tags.Add(new SwiftTag("95Q", Tag95Q_Party));
			if (Tag95R_Party != null)
				tags.Add(new SwiftTag("95R", Tag95R_Party));
			if (Tag19B_Amount != null)
				tags.Add(new SwiftTag("19B", Tag19B_Amount));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "22H") && (i <= 2))
				{
					Tag22H_Indicator = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "98A") && (i <= 3))
				{
					if (Tag98A_Date == null)
						Tag98A_Date = new List<string>();
					Tag98A_Date.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "98B") && (i <= 3))
				{
					if (Tag98B_DateCode == null)
						Tag98B_DateCode = new List<string>();
					Tag98B_DateCode.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "95P") && (i <= 4))
				{
					Tag95P_Party = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "95Q") && (i <= 4))
				{
					Tag95Q_Party = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "95R") && (i <= 4))
				{
					Tag95R_Party = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "19B") && (i <= 5))
				{
					Tag19B_Amount = tag.Value;
					i = 5;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 6))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 6;
				}
			}
        }
        
        public static MT505_SequenceB3 GetMT505_SequenceB3(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT505_SequenceB3.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceB3.Tag16S_EndOfBlock_Value));
			return new MT505_SequenceB3(subBlock);
        }
    }
    
    /// <summary>
    /// Sequence C Settlement Details
    /// <summary>
    public partial class MT505_SequenceC
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "SETDET1";
        /// <summary>
        /// Start Of  Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22H_Indicator { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Subsequence C1 Settlement Parties
        /// <summary>
		public List<MT505_SequenceC1> SequenceC1List { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "SETDET1";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceC()
        {
        }
        
        public MT505_SequenceC(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag22H_Indicator != null)
				tags.AddRange(Tag22H_Indicator.Select(x => new SwiftTag("22H", x)).ToList());
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (SequenceC1List != null)
				tags.AddRange(SequenceC1List.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "22H") && (i <= 2))
				{
					if (Tag22H_Indicator == null)
						Tag22H_Indicator = new List<string>();
					Tag22H_Indicator.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "22F") && (i <= 2))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 2;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 3))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 3;
				}
			}
			SequenceC1List = MT505_SequenceC1.GetMT505_SequenceC1List(tags);
        }
        
        public static MT505_SequenceC GetMT505_SequenceC(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT505_SequenceC.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceC.Tag16S_EndOfBlock_Value));
			return new MT505_SequenceC(subBlock);
        }
    }
    
    /// <summary>
    /// Subsequence C1 Settlement Parties
    /// <summary>
    public partial class MT505_SequenceC1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "SETPRTY1";
        /// <summary>
        /// Start Of The Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95C_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95S_Party { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public string Tag97A_Account { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public string Tag97B_Account { get; set; }
        /// <summary>
        /// Party Contract Narrative
        /// <summary>
		public string Tag70C_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "SETPRTY1";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceC1()
        {
        }
        
        public MT505_SequenceC1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95C_Party != null)
				tags.AddRange(Tag95C_Party.Select(x => new SwiftTag("95C", x)).ToList());
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95S_Party != null)
				tags.AddRange(Tag95S_Party.Select(x => new SwiftTag("95S", x)).ToList());
			if (Tag97A_Account != null)
				tags.Add(new SwiftTag("97A", Tag97A_Account));
			if (Tag97B_Account != null)
				tags.Add(new SwiftTag("97B", Tag97B_Account));
			if (Tag70C_Narrative != null)
				tags.Add(new SwiftTag("70C", Tag70C_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95C") && (i <= 2))
				{
					if (Tag95C_Party == null)
						Tag95C_Party = new List<string>();
					Tag95C_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95S") && (i <= 2))
				{
					if (Tag95S_Party == null)
						Tag95S_Party = new List<string>();
					Tag95S_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "97A") && (i <= 3))
				{
					Tag97A_Account = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "97B") && (i <= 3))
				{
					Tag97B_Account = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "70C") && (i <= 4))
				{
					Tag70C_Narrative = tag.Value;
					i = 4;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 5))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 5;
				}
			}
        }
        
        public static List<MT505_SequenceC1> GetMT505_SequenceC1List(SwiftTagList tags)
        {
			List<MT505_SequenceC1> result = new List<MT505_SequenceC1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT505_SequenceC1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceC1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT505_SequenceC1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceC1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT505_SequenceC1 sequence = new MT505_SequenceC1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Sequence D Cash Settlement Details
    /// <summary>
    public partial class MT505_SequenceD
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "CASHSET1";
        /// <summary>
        /// Start Of  Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public string Tag22F_Indicator { get; set; }
        /// <summary>
        /// Subsequence D1 Cash Parties
        /// <summary>
		public List<MT505_SequenceD1> SequenceD1List { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "CASHSET1";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceD()
        {
        }
        
        public MT505_SequenceD(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag22F_Indicator != null)
				tags.Add(new SwiftTag("22F", Tag22F_Indicator));
			if (SequenceD1List != null)
				tags.AddRange(SequenceD1List.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "22F") && (i <= 2))
				{
					Tag22F_Indicator = tag.Value;
					i = 2;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 3))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 3;
				}
			}
			SequenceD1List = MT505_SequenceD1.GetMT505_SequenceD1List(tags);
        }
        
        public static MT505_SequenceD GetMT505_SequenceD(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT505_SequenceD.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceD.Tag16S_EndOfBlock_Value));
			return new MT505_SequenceD(subBlock);
        }
    }
    
    /// <summary>
    /// Subsequence D1 Cash Parties
    /// <summary>
    public partial class MT505_SequenceD1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "CSHPRTY1";
        /// <summary>
        /// Start Of  Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95S_Party { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97A_Account { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97E_Account { get; set; }
        /// <summary>
        /// Party Contract Narrative
        /// <summary>
		public string Tag70C_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "CSHPRTY1";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceD1()
        {
        }
        
        public MT505_SequenceD1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95S_Party != null)
				tags.AddRange(Tag95S_Party.Select(x => new SwiftTag("95S", x)).ToList());
			if (Tag97A_Account != null)
				tags.AddRange(Tag97A_Account.Select(x => new SwiftTag("97A", x)).ToList());
			if (Tag97E_Account != null)
				tags.AddRange(Tag97E_Account.Select(x => new SwiftTag("97E", x)).ToList());
			if (Tag70C_Narrative != null)
				tags.Add(new SwiftTag("70C", Tag70C_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95S") && (i <= 2))
				{
					if (Tag95S_Party == null)
						Tag95S_Party = new List<string>();
					Tag95S_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "97A") && (i <= 3))
				{
					if (Tag97A_Account == null)
						Tag97A_Account = new List<string>();
					Tag97A_Account.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "97E") && (i <= 3))
				{
					if (Tag97E_Account == null)
						Tag97E_Account = new List<string>();
					Tag97E_Account.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "70C") && (i <= 4))
				{
					Tag70C_Narrative = tag.Value;
					i = 4;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 5))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 5;
				}
			}
        }
        
        public static List<MT505_SequenceD1> GetMT505_SequenceD1List(SwiftTagList tags)
        {
			List<MT505_SequenceD1> result = new List<MT505_SequenceD1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT505_SequenceD1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceD1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT505_SequenceD1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceD1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT505_SequenceD1 sequence = new MT505_SequenceD1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Additional Information
    /// <summary>
    public partial class MT505_SequenceE
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "ADDINFO";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "ADDINFO";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT505_SequenceE()
        {
        }
        
        public MT505_SequenceE(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 3))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 3;
				}
			}
        }
        
        public static MT505_SequenceE GetMT505_SequenceE(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT505_SequenceE.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT505_SequenceE.Tag16S_EndOfBlock_Value));
			return new MT505_SequenceE(subBlock);
        }
    }
}
