//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swift.Net.Mt.Category5
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// MT515 (SRG 2019)
    /// <summary>
    public partial class MT515 : SwiftMessage
    {
        
		public override SwiftBlock4 Block4 { get => new SwiftBlock4(GetBlock4Tags()); set => SetBlock4Tags(value); }

        /// <summary>
        /// General Information
        /// <summary>
		public MT515_SequenceA SequenceA { get; set; }
        /// <summary>
        /// Partial Fill Details
        /// <summary>
		public List<MT515_SequenceB> SequenceBList { get; set; }
        /// <summary>
        /// Confirmation Details
        /// <summary>
		public MT515_SequenceC SequenceC { get; set; }
        /// <summary>
        /// Settlement Details
        /// <summary>
		public MT515_SequenceD SequenceD { get; set; }
        /// <summary>
        /// Other Parties
        /// <summary>
		public List<MT515_SequenceE> SequenceEList { get; set; }
        /// <summary>
        /// Repo Details
        /// <summary>
		public MT515_SequenceF SequenceF { get; set; }
        
        public MT515()
        {
        }
        
        public MT515(SwiftTagList tags)
        {
			SetBlock4Tags(tags);
        }
        
        public virtual SwiftTagList GetBlock4Tags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (SequenceA != null)
				tags.AddRange(SequenceA.GetTags());
			if (SequenceBList != null)
				tags.AddRange(SequenceBList.SelectMany(x => x.GetTags()).ToList());
			if (SequenceC != null)
				tags.AddRange(SequenceC.GetTags());
			if (SequenceD != null)
				tags.AddRange(SequenceD.GetTags());
			if (SequenceEList != null)
				tags.AddRange(SequenceEList.SelectMany(x => x.GetTags()).ToList());
			if (SequenceF != null)
				tags.AddRange(SequenceF.GetTags());
			return tags;
        }
        
        public virtual void SetBlock4Tags(SwiftTagList tags)
        {
			SequenceA = MT515_SequenceA.GetMT515_SequenceA(tags);
			SequenceBList = MT515_SequenceB.GetMT515_SequenceBList(tags);
			SequenceC = MT515_SequenceC.GetMT515_SequenceC(tags);
			SequenceD = MT515_SequenceD.GetMT515_SequenceD(tags);
			SequenceEList = MT515_SequenceE.GetMT515_SequenceEList(tags);
			SequenceF = MT515_SequenceF.GetMT515_SequenceF(tags);
        }
        
        public static MT515 Parse(string message)
        {
			SwiftMessage swiftMessage = new SwiftParser().GetSwiftMessage(message);
			MT515 result = new MT515()
			{
				Block1 = swiftMessage.Block1,
				Block2 = swiftMessage.Block2,
				Block3 = swiftMessage.Block3,
				Block4 = swiftMessage.Block4,
				Block5 = swiftMessage.Block5,
			};
			return result;
        }
        
        public static string Write(MT515 message)
        {
			return new SwiftWriter().GetFinMessage(message);
        }
    }
    
    /// <summary>
    /// General Information
    /// <summary>
    public partial class MT515_SequenceA
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "GENL";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Page Number/Continuation Indicator
        /// <summary>
		public string Tag28E_PageNumberAndContinuationIndicator { get; set; }
        /// <summary>
        /// Sender's Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
        /// <summary>
        /// Function of the Message
        /// <summary>
		public string Tag23G_FunctionOfTheMessage { get; set; }
        /// <summary>
        /// Preparation Date/Time
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Preparation Date/Time
        /// <summary>
		public string Tag98C_DateTime { get; set; }
        /// <summary>
        /// Trade Date/Time
        /// <summary>
		public string Tag98E_DateTime { get; set; }
        /// <summary>
        /// Trade Transaction Type Indicator
        /// <summary>
		public string Tag22F_Indicator { get; set; }
        /// <summary>
        /// Linkages
        /// <summary>
		public List<MT515_SequenceA1> SequenceA1List { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "GENL";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT515_SequenceA()
        {
        }
        
        public MT515_SequenceA(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag28E_PageNumberAndContinuationIndicator != null)
				tags.Add(new SwiftTag("28E", Tag28E_PageNumberAndContinuationIndicator));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag23G_FunctionOfTheMessage != null)
				tags.Add(new SwiftTag("23G", Tag23G_FunctionOfTheMessage));
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98C_DateTime != null)
				tags.Add(new SwiftTag("98C", Tag98C_DateTime));
			if (Tag98E_DateTime != null)
				tags.Add(new SwiftTag("98E", Tag98E_DateTime));
			if (Tag22F_Indicator != null)
				tags.Add(new SwiftTag("22F", Tag22F_Indicator));
			if (SequenceA1List != null)
				tags.AddRange(SequenceA1List.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "28E") && (i <= 2))
				{
					Tag28E_PageNumberAndContinuationIndicator = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "20C") && (i <= 3))
				{
					Tag20C_Reference = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "23G") && (i <= 4))
				{
					Tag23G_FunctionOfTheMessage = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "98A") && (i <= 5))
				{
					Tag98A_Date = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "98C") && (i <= 5))
				{
					Tag98C_DateTime = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "98E") && (i <= 5))
				{
					Tag98E_DateTime = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "22F") && (i <= 6))
				{
					Tag22F_Indicator = tag.Value;
					i = 6;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 7))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 7;
				}
			}
			SequenceA1List = MT515_SequenceA1.GetMT515_SequenceA1List(tags);
        }
        
        public static MT515_SequenceA GetMT515_SequenceA(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT515_SequenceA.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceA.Tag16S_EndOfBlock_Value));
			return new MT515_SequenceA(subBlock);
        }
    }
    
    /// <summary>
    /// Linkages
    /// <summary>
    public partial class MT515_SequenceA1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "LINK";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Linked Transaction Number Identification
        /// <summary>
		public string Tag13A_NumberIdentification { get; set; }
        /// <summary>
        /// Number Identification
        /// <summary>
		public string Tag13B_NumberIdentification { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public string Tag20U_Reference { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "LINK";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT515_SequenceA1()
        {
        }
        
        public MT515_SequenceA1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag13A_NumberIdentification != null)
				tags.Add(new SwiftTag("13A", Tag13A_NumberIdentification));
			if (Tag13B_NumberIdentification != null)
				tags.Add(new SwiftTag("13B", Tag13B_NumberIdentification));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag20U_Reference != null)
				tags.Add(new SwiftTag("20U", Tag20U_Reference));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "13A") && (i <= 2))
				{
					Tag13A_NumberIdentification = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "13B") && (i <= 2))
				{
					Tag13B_NumberIdentification = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "20C") && (i <= 3))
				{
					Tag20C_Reference = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "20U") && (i <= 3))
				{
					Tag20U_Reference = tag.Value;
					i = 3;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 4))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 4;
				}
			}
        }
        
        public static List<MT515_SequenceA1> GetMT515_SequenceA1List(SwiftTagList tags)
        {
			List<MT515_SequenceA1> result = new List<MT515_SequenceA1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT515_SequenceA1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceA1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT515_SequenceA1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceA1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT515_SequenceA1 sequence = new MT515_SequenceA1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Partial Fill Details
    /// <summary>
    public partial class MT515_SequenceB
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "PAFILL";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Quantity of Financial
        /// <summary>
		public string Tag36B_QuantityOfFinancialInstrument { get; set; }
        /// <summary>
        /// Deal Price
        /// <summary>
		public string Tag90A_Price { get; set; }
        /// <summary>
        /// Deal Price
        /// <summary>
		public string Tag90B_Price { get; set; }
        /// <summary>
        /// Type Of Price Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Trade Date/Time
        /// <summary>
		public string Tag98E_DateTime { get; set; }
        /// <summary>
        /// Trade Date/Time
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Trade Date/Time
        /// <summary>
		public string Tag98B_DateCode { get; set; }
        /// <summary>
        /// Trade Date/Time
        /// <summary>
		public string Tag98C_DateTime { get; set; }
        /// <summary>
        /// Place of Trade
        /// <summary>
		public List<string> Tag94B_Place { get; set; }
        /// <summary>
        /// Place of Trade
        /// <summary>
		public List<string> Tag94L_Place { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "PAFILL";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT515_SequenceB()
        {
        }
        
        public MT515_SequenceB(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag36B_QuantityOfFinancialInstrument != null)
				tags.Add(new SwiftTag("36B", Tag36B_QuantityOfFinancialInstrument));
			if (Tag90A_Price != null)
				tags.Add(new SwiftTag("90A", Tag90A_Price));
			if (Tag90B_Price != null)
				tags.Add(new SwiftTag("90B", Tag90B_Price));
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (Tag98E_DateTime != null)
				tags.Add(new SwiftTag("98E", Tag98E_DateTime));
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98B_DateCode != null)
				tags.Add(new SwiftTag("98B", Tag98B_DateCode));
			if (Tag98C_DateTime != null)
				tags.Add(new SwiftTag("98C", Tag98C_DateTime));
			if (Tag94B_Place != null)
				tags.AddRange(Tag94B_Place.Select(x => new SwiftTag("94B", x)).ToList());
			if (Tag94L_Place != null)
				tags.AddRange(Tag94L_Place.Select(x => new SwiftTag("94L", x)).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "36B") && (i <= 2))
				{
					Tag36B_QuantityOfFinancialInstrument = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "90A") && (i <= 3))
				{
					Tag90A_Price = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "90B") && (i <= 3))
				{
					Tag90B_Price = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "22F") && (i <= 4))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "98E") && (i <= 5))
				{
					Tag98E_DateTime = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "98A") && (i <= 5))
				{
					Tag98A_Date = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "98B") && (i <= 5))
				{
					Tag98B_DateCode = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "98C") && (i <= 5))
				{
					Tag98C_DateTime = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "94B") && (i <= 6))
				{
					if (Tag94B_Place == null)
						Tag94B_Place = new List<string>();
					Tag94B_Place.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "94L") && (i <= 6))
				{
					if (Tag94L_Place == null)
						Tag94L_Place = new List<string>();
					Tag94L_Place.Add(tag.Value);
					i = 6;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 7))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 7;
				}
			}
        }
        
        public static List<MT515_SequenceB> GetMT515_SequenceBList(SwiftTagList tags)
        {
			List<MT515_SequenceB> result = new List<MT515_SequenceB>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT515_SequenceB.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceB.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT515_SequenceB.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceB.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT515_SequenceB sequence = new MT515_SequenceB(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Confirmation Details
    /// <summary>
    public partial class MT515_SequenceC
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "CONFDET";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Trade Date/Time
        /// <summary>
		public List<string> Tag98E_DateTime { get; set; }
        /// <summary>
        /// Trade/Settlement/Net Asset Value Calculation Date
        /// <summary>
		public List<string> Tag98A_Date { get; set; }
        /// <summary>
        /// Trade/Settlement Date
        /// <summary>
		public List<string> Tag98B_DateCode { get; set; }
        /// <summary>
        /// Trade/Settlement/Net Asset Value Calculation Date
        /// <summary>
		public List<string> Tag98C_DateTime { get; set; }
        /// <summary>
        /// Price
        /// <summary>
		public List<string> Tag90A_Price { get; set; }
        /// <summary>
        /// Price
        /// <summary>
		public List<string> Tag90B_Price { get; set; }
        /// <summary>
        /// Rate
        /// <summary>
		public List<string> Tag92A_Rate { get; set; }
        /// <summary>
        /// Number Count
        /// <summary>
		public List<string> Tag99A_NumberCount { get; set; }
        /// <summary>
        /// Place
        /// <summary>
		public List<string> Tag94B_Place { get; set; }
        /// <summary>
        /// Place of Safekeeping
        /// <summary>
		public List<string> Tag94C_Place { get; set; }
        /// <summary>
        /// Place
        /// <summary>
		public List<string> Tag94F_Place { get; set; }
        /// <summary>
        /// Place
        /// <summary>
		public List<string> Tag94L_Place { get; set; }
        /// <summary>
        /// Settlement Amount
        /// <summary>
		public string Tag19A_Amount { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22H_Indicator { get; set; }
        /// <summary>
        /// Currency
        /// <summary>
		public string Tag11A_Currency { get; set; }
        /// <summary>
        /// Confirmation Parties
        /// <summary>
		public List<MT515_SequenceC1> SequenceC1List { get; set; }
        /// <summary>
        /// Quantity of Financial Instrument Confirmed
        /// <summary>
		public List<string> Tag36B_QuantityofFinancialInstrument { get; set; }
        /// <summary>
        /// Identification Of The Financial Instrument_C_35B
        /// <summary>
		public string Tag35B_IdentificationOfFinancialInstrument { get; set; }
        /// <summary>
        /// Financial Instrument Attributes
        /// <summary>
		public MT515_SequenceC2 SequenceC2 { get; set; }
        /// <summary>
        /// Number Identification
        /// <summary>
		public List<string> Tag13B_NumberIdentification { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public List<string> Tag70E_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "CONFDET";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT515_SequenceC()
        {
        }
        
        public MT515_SequenceC(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag98E_DateTime != null)
				tags.AddRange(Tag98E_DateTime.Select(x => new SwiftTag("98E", x)).ToList());
			if (Tag98A_Date != null)
				tags.AddRange(Tag98A_Date.Select(x => new SwiftTag("98A", x)).ToList());
			if (Tag98B_DateCode != null)
				tags.AddRange(Tag98B_DateCode.Select(x => new SwiftTag("98B", x)).ToList());
			if (Tag98C_DateTime != null)
				tags.AddRange(Tag98C_DateTime.Select(x => new SwiftTag("98C", x)).ToList());
			if (Tag90A_Price != null)
				tags.AddRange(Tag90A_Price.Select(x => new SwiftTag("90A", x)).ToList());
			if (Tag90B_Price != null)
				tags.AddRange(Tag90B_Price.Select(x => new SwiftTag("90B", x)).ToList());
			if (Tag92A_Rate != null)
				tags.AddRange(Tag92A_Rate.Select(x => new SwiftTag("92A", x)).ToList());
			if (Tag99A_NumberCount != null)
				tags.AddRange(Tag99A_NumberCount.Select(x => new SwiftTag("99A", x)).ToList());
			if (Tag94B_Place != null)
				tags.AddRange(Tag94B_Place.Select(x => new SwiftTag("94B", x)).ToList());
			if (Tag94C_Place != null)
				tags.AddRange(Tag94C_Place.Select(x => new SwiftTag("94C", x)).ToList());
			if (Tag94F_Place != null)
				tags.AddRange(Tag94F_Place.Select(x => new SwiftTag("94F", x)).ToList());
			if (Tag94L_Place != null)
				tags.AddRange(Tag94L_Place.Select(x => new SwiftTag("94L", x)).ToList());
			if (Tag19A_Amount != null)
				tags.Add(new SwiftTag("19A", Tag19A_Amount));
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (Tag22H_Indicator != null)
				tags.AddRange(Tag22H_Indicator.Select(x => new SwiftTag("22H", x)).ToList());
			if (Tag11A_Currency != null)
				tags.Add(new SwiftTag("11A", Tag11A_Currency));
			if (SequenceC1List != null)
				tags.AddRange(SequenceC1List.SelectMany(x => x.GetTags()).ToList());
			if (Tag36B_QuantityofFinancialInstrument != null)
				tags.AddRange(Tag36B_QuantityofFinancialInstrument.Select(x => new SwiftTag("36B", x)).ToList());
			if (Tag35B_IdentificationOfFinancialInstrument != null)
				tags.Add(new SwiftTag("35B", Tag35B_IdentificationOfFinancialInstrument));
			if (SequenceC2 != null)
				tags.AddRange(SequenceC2.GetTags());
			if (Tag13B_NumberIdentification != null)
				tags.AddRange(Tag13B_NumberIdentification.Select(x => new SwiftTag("13B", x)).ToList());
			if (Tag70E_Narrative != null)
				tags.AddRange(Tag70E_Narrative.Select(x => new SwiftTag("70E", x)).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "98E") && (i <= 2))
				{
					if (Tag98E_DateTime == null)
						Tag98E_DateTime = new List<string>();
					Tag98E_DateTime.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "98A") && (i <= 2))
				{
					if (Tag98A_Date == null)
						Tag98A_Date = new List<string>();
					Tag98A_Date.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "98B") && (i <= 2))
				{
					if (Tag98B_DateCode == null)
						Tag98B_DateCode = new List<string>();
					Tag98B_DateCode.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "98C") && (i <= 2))
				{
					if (Tag98C_DateTime == null)
						Tag98C_DateTime = new List<string>();
					Tag98C_DateTime.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "90A") && (i <= 3))
				{
					if (Tag90A_Price == null)
						Tag90A_Price = new List<string>();
					Tag90A_Price.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "90B") && (i <= 3))
				{
					if (Tag90B_Price == null)
						Tag90B_Price = new List<string>();
					Tag90B_Price.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "92A") && (i <= 4))
				{
					if (Tag92A_Rate == null)
						Tag92A_Rate = new List<string>();
					Tag92A_Rate.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "99A") && (i <= 5))
				{
					if (Tag99A_NumberCount == null)
						Tag99A_NumberCount = new List<string>();
					Tag99A_NumberCount.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "94B") && (i <= 6))
				{
					if (Tag94B_Place == null)
						Tag94B_Place = new List<string>();
					Tag94B_Place.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "94C") && (i <= 6))
				{
					if (Tag94C_Place == null)
						Tag94C_Place = new List<string>();
					Tag94C_Place.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "94F") && (i <= 6))
				{
					if (Tag94F_Place == null)
						Tag94F_Place = new List<string>();
					Tag94F_Place.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "94L") && (i <= 6))
				{
					if (Tag94L_Place == null)
						Tag94L_Place = new List<string>();
					Tag94L_Place.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "19A") && (i <= 7))
				{
					Tag19A_Amount = tag.Value;
					i = 7;
				}
				else if ((tag.Name == "22F") && (i <= 8))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "22H") && (i <= 8))
				{
					if (Tag22H_Indicator == null)
						Tag22H_Indicator = new List<string>();
					Tag22H_Indicator.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "11A") && (i <= 9))
				{
					Tag11A_Currency = tag.Value;
					i = 9;
				}
				else if ((tag.Name == "36B") && (i <= 10))
				{
					if (Tag36B_QuantityofFinancialInstrument == null)
						Tag36B_QuantityofFinancialInstrument = new List<string>();
					Tag36B_QuantityofFinancialInstrument.Add(tag.Value);
					i = 10;
				}
				else if ((tag.Name == "35B") && (i <= 11))
				{
					Tag35B_IdentificationOfFinancialInstrument = tag.Value;
					i = 11;
				}
				else if ((tag.Name == "13B") && (i <= 12))
				{
					if (Tag13B_NumberIdentification == null)
						Tag13B_NumberIdentification = new List<string>();
					Tag13B_NumberIdentification.Add(tag.Value);
					i = 12;
				}
				else if ((tag.Name == "70E") && (i <= 13))
				{
					if (Tag70E_Narrative == null)
						Tag70E_Narrative = new List<string>();
					Tag70E_Narrative.Add(tag.Value);
					i = 13;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 14))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 14;
				}
			}
			SequenceC1List = MT515_SequenceC1.GetMT515_SequenceC1List(tags);
			SequenceC2 = MT515_SequenceC2.GetMT515_SequenceC2(tags);
        }
        
        public static MT515_SequenceC GetMT515_SequenceC(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT515_SequenceC.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceC.Tag16S_EndOfBlock_Value));
			return new MT515_SequenceC(subBlock);
        }
    }
    
    /// <summary>
    /// Confirmation Parties
    /// <summary>
    public partial class MT515_SequenceC1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "CONFPRTY";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95S_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95L_Party { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97A_Account { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97B_Account { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97E_Account { get; set; }
        /// <summary>
        /// Processing Date/Time
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Processing Date/Time
        /// <summary>
		public string Tag98C_DateTime { get; set; }
        /// <summary>
        /// Sender's Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public List<string> Tag70C_Narrative { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public List<string> Tag70E_Narrative { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "CONFPRTY";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT515_SequenceC1()
        {
        }
        
        public MT515_SequenceC1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95S_Party != null)
				tags.AddRange(Tag95S_Party.Select(x => new SwiftTag("95S", x)).ToList());
			if (Tag95L_Party != null)
				tags.AddRange(Tag95L_Party.Select(x => new SwiftTag("95L", x)).ToList());
			if (Tag97A_Account != null)
				tags.AddRange(Tag97A_Account.Select(x => new SwiftTag("97A", x)).ToList());
			if (Tag97B_Account != null)
				tags.AddRange(Tag97B_Account.Select(x => new SwiftTag("97B", x)).ToList());
			if (Tag97E_Account != null)
				tags.AddRange(Tag97E_Account.Select(x => new SwiftTag("97E", x)).ToList());
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98C_DateTime != null)
				tags.Add(new SwiftTag("98C", Tag98C_DateTime));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag70C_Narrative != null)
				tags.AddRange(Tag70C_Narrative.Select(x => new SwiftTag("70C", x)).ToList());
			if (Tag70E_Narrative != null)
				tags.AddRange(Tag70E_Narrative.Select(x => new SwiftTag("70E", x)).ToList());
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95S") && (i <= 2))
				{
					if (Tag95S_Party == null)
						Tag95S_Party = new List<string>();
					Tag95S_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95L") && (i <= 2))
				{
					if (Tag95L_Party == null)
						Tag95L_Party = new List<string>();
					Tag95L_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "97A") && (i <= 3))
				{
					if (Tag97A_Account == null)
						Tag97A_Account = new List<string>();
					Tag97A_Account.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "97B") && (i <= 3))
				{
					if (Tag97B_Account == null)
						Tag97B_Account = new List<string>();
					Tag97B_Account.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "97E") && (i <= 3))
				{
					if (Tag97E_Account == null)
						Tag97E_Account = new List<string>();
					Tag97E_Account.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "98A") && (i <= 4))
				{
					Tag98A_Date = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "98C") && (i <= 4))
				{
					Tag98C_DateTime = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "20C") && (i <= 5))
				{
					Tag20C_Reference = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "70C") && (i <= 6))
				{
					if (Tag70C_Narrative == null)
						Tag70C_Narrative = new List<string>();
					Tag70C_Narrative.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "70E") && (i <= 6))
				{
					if (Tag70E_Narrative == null)
						Tag70E_Narrative = new List<string>();
					Tag70E_Narrative.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "22F") && (i <= 7))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 7;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 8))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 8;
				}
			}
        }
        
        public static List<MT515_SequenceC1> GetMT515_SequenceC1List(SwiftTagList tags)
        {
			List<MT515_SequenceC1> result = new List<MT515_SequenceC1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT515_SequenceC1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceC1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT515_SequenceC1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceC1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT515_SequenceC1 sequence = new MT515_SequenceC1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Financial Instrument Attributes
    /// <summary>
    public partial class MT515_SequenceC2
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "FIA";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Place of Listing
        /// <summary>
		public string Tag94B_Place { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Type of Financial Instrument
        /// <summary>
		public List<string> Tag12A_TypeOfFinancialInstrument { get; set; }
        /// <summary>
        /// Type of Financial Instrument
        /// <summary>
		public List<string> Tag12C_TypeOfFinancialInstrument { get; set; }
        /// <summary>
        /// Type of Financial Instrument
        /// <summary>
		public List<string> Tag12B_TypeOfFinancialInstrument { get; set; }
        /// <summary>
        /// Currency
        /// <summary>
		public string Tag11A_Currency { get; set; }
        /// <summary>
        /// Processing Date/Time
        /// <summary>
		public List<string> Tag98A_Date { get; set; }
        /// <summary>
        /// Rate
        /// <summary>
		public List<string> Tag92A_Rate { get; set; }
        /// <summary>
        /// Number Identification
        /// <summary>
		public List<string> Tag13A_NumberIdentification { get; set; }
        /// <summary>
        /// Number Identification
        /// <summary>
		public List<string> Tag13B_NumberIdentification { get; set; }
        /// <summary>
        /// Flag
        /// <summary>
		public List<string> Tag17B_Flag { get; set; }
        /// <summary>
        /// Price
        /// <summary>
		public List<string> Tag90A_Price { get; set; }
        /// <summary>
        /// Price
        /// <summary>
		public List<string> Tag90B_Price { get; set; }
        /// <summary>
        /// Quantity of Financial Instrument Confirmed
        /// <summary>
		public List<string> Tag36B_QuantityOfFinancialInstrument { get; set; }
        /// <summary>
        /// Identification Of The Financial Instrument_C_35B
        /// <summary>
		public List<string> Tag35B_IdentificationOfFinancialInstrument { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public string Tag70E_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "FIA";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT515_SequenceC2()
        {
        }
        
        public MT515_SequenceC2(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag94B_Place != null)
				tags.Add(new SwiftTag("94B", Tag94B_Place));
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (Tag12A_TypeOfFinancialInstrument != null)
				tags.AddRange(Tag12A_TypeOfFinancialInstrument.Select(x => new SwiftTag("12A", x)).ToList());
			if (Tag12C_TypeOfFinancialInstrument != null)
				tags.AddRange(Tag12C_TypeOfFinancialInstrument.Select(x => new SwiftTag("12C", x)).ToList());
			if (Tag12B_TypeOfFinancialInstrument != null)
				tags.AddRange(Tag12B_TypeOfFinancialInstrument.Select(x => new SwiftTag("12B", x)).ToList());
			if (Tag11A_Currency != null)
				tags.Add(new SwiftTag("11A", Tag11A_Currency));
			if (Tag98A_Date != null)
				tags.AddRange(Tag98A_Date.Select(x => new SwiftTag("98A", x)).ToList());
			if (Tag92A_Rate != null)
				tags.AddRange(Tag92A_Rate.Select(x => new SwiftTag("92A", x)).ToList());
			if (Tag13A_NumberIdentification != null)
				tags.AddRange(Tag13A_NumberIdentification.Select(x => new SwiftTag("13A", x)).ToList());
			if (Tag13B_NumberIdentification != null)
				tags.AddRange(Tag13B_NumberIdentification.Select(x => new SwiftTag("13B", x)).ToList());
			if (Tag17B_Flag != null)
				tags.AddRange(Tag17B_Flag.Select(x => new SwiftTag("17B", x)).ToList());
			if (Tag90A_Price != null)
				tags.AddRange(Tag90A_Price.Select(x => new SwiftTag("90A", x)).ToList());
			if (Tag90B_Price != null)
				tags.AddRange(Tag90B_Price.Select(x => new SwiftTag("90B", x)).ToList());
			if (Tag36B_QuantityOfFinancialInstrument != null)
				tags.AddRange(Tag36B_QuantityOfFinancialInstrument.Select(x => new SwiftTag("36B", x)).ToList());
			if (Tag35B_IdentificationOfFinancialInstrument != null)
				tags.AddRange(Tag35B_IdentificationOfFinancialInstrument.Select(x => new SwiftTag("35B", x)).ToList());
			if (Tag70E_Narrative != null)
				tags.Add(new SwiftTag("70E", Tag70E_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "94B") && (i <= 2))
				{
					Tag94B_Place = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "22F") && (i <= 3))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "12A") && (i <= 4))
				{
					if (Tag12A_TypeOfFinancialInstrument == null)
						Tag12A_TypeOfFinancialInstrument = new List<string>();
					Tag12A_TypeOfFinancialInstrument.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "12C") && (i <= 4))
				{
					if (Tag12C_TypeOfFinancialInstrument == null)
						Tag12C_TypeOfFinancialInstrument = new List<string>();
					Tag12C_TypeOfFinancialInstrument.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "12B") && (i <= 4))
				{
					if (Tag12B_TypeOfFinancialInstrument == null)
						Tag12B_TypeOfFinancialInstrument = new List<string>();
					Tag12B_TypeOfFinancialInstrument.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "11A") && (i <= 5))
				{
					Tag11A_Currency = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "98A") && (i <= 6))
				{
					if (Tag98A_Date == null)
						Tag98A_Date = new List<string>();
					Tag98A_Date.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "92A") && (i <= 7))
				{
					if (Tag92A_Rate == null)
						Tag92A_Rate = new List<string>();
					Tag92A_Rate.Add(tag.Value);
					i = 7;
				}
				else if ((tag.Name == "13A") && (i <= 8))
				{
					if (Tag13A_NumberIdentification == null)
						Tag13A_NumberIdentification = new List<string>();
					Tag13A_NumberIdentification.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "13B") && (i <= 8))
				{
					if (Tag13B_NumberIdentification == null)
						Tag13B_NumberIdentification = new List<string>();
					Tag13B_NumberIdentification.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "17B") && (i <= 9))
				{
					if (Tag17B_Flag == null)
						Tag17B_Flag = new List<string>();
					Tag17B_Flag.Add(tag.Value);
					i = 9;
				}
				else if ((tag.Name == "90A") && (i <= 10))
				{
					if (Tag90A_Price == null)
						Tag90A_Price = new List<string>();
					Tag90A_Price.Add(tag.Value);
					i = 10;
				}
				else if ((tag.Name == "90B") && (i <= 10))
				{
					if (Tag90B_Price == null)
						Tag90B_Price = new List<string>();
					Tag90B_Price.Add(tag.Value);
					i = 10;
				}
				else if ((tag.Name == "36B") && (i <= 11))
				{
					if (Tag36B_QuantityOfFinancialInstrument == null)
						Tag36B_QuantityOfFinancialInstrument = new List<string>();
					Tag36B_QuantityOfFinancialInstrument.Add(tag.Value);
					i = 11;
				}
				else if ((tag.Name == "35B") && (i <= 12))
				{
					if (Tag35B_IdentificationOfFinancialInstrument == null)
						Tag35B_IdentificationOfFinancialInstrument = new List<string>();
					Tag35B_IdentificationOfFinancialInstrument.Add(tag.Value);
					i = 12;
				}
				else if ((tag.Name == "70E") && (i <= 13))
				{
					Tag70E_Narrative = tag.Value;
					i = 13;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 14))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 14;
				}
			}
        }
        
        public static MT515_SequenceC2 GetMT515_SequenceC2(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT515_SequenceC2.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceC2.Tag16S_EndOfBlock_Value));
			return new MT515_SequenceC2(subBlock);
        }
    }
    
    /// <summary>
    /// Settlement Details
    /// <summary>
    public partial class MT515_SequenceD
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "SETDET";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Currency
        /// <summary>
		public string Tag11A_Currency { get; set; }
        /// <summary>
        /// Settlement Parties
        /// <summary>
		public List<MT515_SequenceD1> SequenceD1List { get; set; }
        /// <summary>
        /// Cash Parties
        /// <summary>
		public List<MT515_SequenceD2> SequenceD2List { get; set; }
        /// <summary>
        /// Amounts
        /// <summary>
		public List<MT515_SequenceD3> SequenceD3List { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "SETDET";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT515_SequenceD()
        {
        }
        
        public MT515_SequenceD(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (Tag11A_Currency != null)
				tags.Add(new SwiftTag("11A", Tag11A_Currency));
			if (SequenceD1List != null)
				tags.AddRange(SequenceD1List.SelectMany(x => x.GetTags()).ToList());
			if (SequenceD2List != null)
				tags.AddRange(SequenceD2List.SelectMany(x => x.GetTags()).ToList());
			if (SequenceD3List != null)
				tags.AddRange(SequenceD3List.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "22F") && (i <= 2))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "11A") && (i <= 3))
				{
					Tag11A_Currency = tag.Value;
					i = 3;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 4))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 4;
				}
			}
			SequenceD1List = MT515_SequenceD1.GetMT515_SequenceD1List(tags);
			SequenceD2List = MT515_SequenceD2.GetMT515_SequenceD2List(tags);
			SequenceD3List = MT515_SequenceD3.GetMT515_SequenceD3List(tags);
        }
        
        public static MT515_SequenceD GetMT515_SequenceD(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT515_SequenceD.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceD.Tag16S_EndOfBlock_Value));
			return new MT515_SequenceD(subBlock);
        }
    }
    
    /// <summary>
    /// Settlement Parties
    /// <summary>
    public partial class MT515_SequenceD1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "SETPRTY";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95C_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95S_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95L_Party { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public string Tag97A_Account { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public string Tag97B_Account { get; set; }
        /// <summary>
        /// Processing Date/Time
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Processing Date/Time
        /// <summary>
		public string Tag98C_DateTime { get; set; }
        /// <summary>
        /// Processing Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public List<string> Tag70C_Narrative { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public List<string> Tag70D_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "SETPRTY";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT515_SequenceD1()
        {
        }
        
        public MT515_SequenceD1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95C_Party != null)
				tags.AddRange(Tag95C_Party.Select(x => new SwiftTag("95C", x)).ToList());
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95S_Party != null)
				tags.AddRange(Tag95S_Party.Select(x => new SwiftTag("95S", x)).ToList());
			if (Tag95L_Party != null)
				tags.AddRange(Tag95L_Party.Select(x => new SwiftTag("95L", x)).ToList());
			if (Tag97A_Account != null)
				tags.Add(new SwiftTag("97A", Tag97A_Account));
			if (Tag97B_Account != null)
				tags.Add(new SwiftTag("97B", Tag97B_Account));
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98C_DateTime != null)
				tags.Add(new SwiftTag("98C", Tag98C_DateTime));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag70C_Narrative != null)
				tags.AddRange(Tag70C_Narrative.Select(x => new SwiftTag("70C", x)).ToList());
			if (Tag70D_Narrative != null)
				tags.AddRange(Tag70D_Narrative.Select(x => new SwiftTag("70D", x)).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95C") && (i <= 2))
				{
					if (Tag95C_Party == null)
						Tag95C_Party = new List<string>();
					Tag95C_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95S") && (i <= 2))
				{
					if (Tag95S_Party == null)
						Tag95S_Party = new List<string>();
					Tag95S_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95L") && (i <= 2))
				{
					if (Tag95L_Party == null)
						Tag95L_Party = new List<string>();
					Tag95L_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "97A") && (i <= 3))
				{
					Tag97A_Account = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "97B") && (i <= 3))
				{
					Tag97B_Account = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "98A") && (i <= 4))
				{
					Tag98A_Date = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "98C") && (i <= 4))
				{
					Tag98C_DateTime = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "20C") && (i <= 5))
				{
					Tag20C_Reference = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "70C") && (i <= 6))
				{
					if (Tag70C_Narrative == null)
						Tag70C_Narrative = new List<string>();
					Tag70C_Narrative.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "70D") && (i <= 6))
				{
					if (Tag70D_Narrative == null)
						Tag70D_Narrative = new List<string>();
					Tag70D_Narrative.Add(tag.Value);
					i = 6;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 7))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 7;
				}
			}
        }
        
        public static List<MT515_SequenceD1> GetMT515_SequenceD1List(SwiftTagList tags)
        {
			List<MT515_SequenceD1> result = new List<MT515_SequenceD1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT515_SequenceD1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceD1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT515_SequenceD1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceD1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT515_SequenceD1 sequence = new MT515_SequenceD1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Cash Parties
    /// <summary>
    public partial class MT515_SequenceD2
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "CSHPRTY";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95S_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95L_Party { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97A_Account { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97E_Account { get; set; }
        /// <summary>
        /// Processing Date/Time
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Processing Date/Time
        /// <summary>
		public string Tag98C_DateTime { get; set; }
        /// <summary>
        /// Processing Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public List<string> Tag70C_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "CSHPRTY";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT515_SequenceD2()
        {
        }
        
        public MT515_SequenceD2(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95S_Party != null)
				tags.AddRange(Tag95S_Party.Select(x => new SwiftTag("95S", x)).ToList());
			if (Tag95L_Party != null)
				tags.AddRange(Tag95L_Party.Select(x => new SwiftTag("95L", x)).ToList());
			if (Tag97A_Account != null)
				tags.AddRange(Tag97A_Account.Select(x => new SwiftTag("97A", x)).ToList());
			if (Tag97E_Account != null)
				tags.AddRange(Tag97E_Account.Select(x => new SwiftTag("97E", x)).ToList());
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98C_DateTime != null)
				tags.Add(new SwiftTag("98C", Tag98C_DateTime));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag70C_Narrative != null)
				tags.AddRange(Tag70C_Narrative.Select(x => new SwiftTag("70C", x)).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95S") && (i <= 2))
				{
					if (Tag95S_Party == null)
						Tag95S_Party = new List<string>();
					Tag95S_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95L") && (i <= 2))
				{
					if (Tag95L_Party == null)
						Tag95L_Party = new List<string>();
					Tag95L_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "97A") && (i <= 3))
				{
					if (Tag97A_Account == null)
						Tag97A_Account = new List<string>();
					Tag97A_Account.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "97E") && (i <= 3))
				{
					if (Tag97E_Account == null)
						Tag97E_Account = new List<string>();
					Tag97E_Account.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "98A") && (i <= 4))
				{
					Tag98A_Date = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "98C") && (i <= 4))
				{
					Tag98C_DateTime = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "20C") && (i <= 5))
				{
					Tag20C_Reference = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "70C") && (i <= 6))
				{
					if (Tag70C_Narrative == null)
						Tag70C_Narrative = new List<string>();
					Tag70C_Narrative.Add(tag.Value);
					i = 6;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 7))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 7;
				}
			}
        }
        
        public static List<MT515_SequenceD2> GetMT515_SequenceD2List(SwiftTagList tags)
        {
			List<MT515_SequenceD2> result = new List<MT515_SequenceD2>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT515_SequenceD2.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceD2.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT515_SequenceD2.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceD2.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT515_SequenceD2 sequence = new MT515_SequenceD2(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Amounts
    /// <summary>
    public partial class MT515_SequenceD3
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "AMT";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Flag
        /// <summary>
		public List<string> Tag17B_Flag { get; set; }
        /// <summary>
        /// Amount
        /// <summary>
		public List<string> Tag19A_Amount { get; set; }
        /// <summary>
        /// Value Date
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Value Date
        /// <summary>
		public string Tag98C_DateTime { get; set; }
        /// <summary>
        /// Exchange Rate
        /// <summary>
		public string Tag92B_Rate { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "AMT";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT515_SequenceD3()
        {
        }
        
        public MT515_SequenceD3(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag17B_Flag != null)
				tags.AddRange(Tag17B_Flag.Select(x => new SwiftTag("17B", x)).ToList());
			if (Tag19A_Amount != null)
				tags.AddRange(Tag19A_Amount.Select(x => new SwiftTag("19A", x)).ToList());
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98C_DateTime != null)
				tags.Add(new SwiftTag("98C", Tag98C_DateTime));
			if (Tag92B_Rate != null)
				tags.Add(new SwiftTag("92B", Tag92B_Rate));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "17B") && (i <= 2))
				{
					if (Tag17B_Flag == null)
						Tag17B_Flag = new List<string>();
					Tag17B_Flag.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "19A") && (i <= 3))
				{
					if (Tag19A_Amount == null)
						Tag19A_Amount = new List<string>();
					Tag19A_Amount.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "98A") && (i <= 4))
				{
					Tag98A_Date = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "98C") && (i <= 4))
				{
					Tag98C_DateTime = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "92B") && (i <= 5))
				{
					Tag92B_Rate = tag.Value;
					i = 5;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 6))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 6;
				}
			}
        }
        
        public static List<MT515_SequenceD3> GetMT515_SequenceD3List(SwiftTagList tags)
        {
			List<MT515_SequenceD3> result = new List<MT515_SequenceD3>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT515_SequenceD3.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceD3.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT515_SequenceD3.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceD3.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT515_SequenceD3 sequence = new MT515_SequenceD3(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Other Parties
    /// <summary>
    public partial class MT515_SequenceE
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "OTHRPRTY";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95S_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95L_Party { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public List<string> Tag97A_Account { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public List<string> Tag97B_Account { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97E_Account { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public List<string> Tag70C_Narrative { get; set; }
        /// <summary>
        /// Processing Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "OTHRPRTY";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT515_SequenceE()
        {
        }
        
        public MT515_SequenceE(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95S_Party != null)
				tags.AddRange(Tag95S_Party.Select(x => new SwiftTag("95S", x)).ToList());
			if (Tag95L_Party != null)
				tags.AddRange(Tag95L_Party.Select(x => new SwiftTag("95L", x)).ToList());
			if (Tag97A_Account != null)
				tags.AddRange(Tag97A_Account.Select(x => new SwiftTag("97A", x)).ToList());
			if (Tag97B_Account != null)
				tags.AddRange(Tag97B_Account.Select(x => new SwiftTag("97B", x)).ToList());
			if (Tag97E_Account != null)
				tags.AddRange(Tag97E_Account.Select(x => new SwiftTag("97E", x)).ToList());
			if (Tag70C_Narrative != null)
				tags.AddRange(Tag70C_Narrative.Select(x => new SwiftTag("70C", x)).ToList());
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95S") && (i <= 2))
				{
					if (Tag95S_Party == null)
						Tag95S_Party = new List<string>();
					Tag95S_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95L") && (i <= 2))
				{
					if (Tag95L_Party == null)
						Tag95L_Party = new List<string>();
					Tag95L_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "97A") && (i <= 3))
				{
					if (Tag97A_Account == null)
						Tag97A_Account = new List<string>();
					Tag97A_Account.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "97B") && (i <= 3))
				{
					if (Tag97B_Account == null)
						Tag97B_Account = new List<string>();
					Tag97B_Account.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "97E") && (i <= 3))
				{
					if (Tag97E_Account == null)
						Tag97E_Account = new List<string>();
					Tag97E_Account.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "70C") && (i <= 4))
				{
					if (Tag70C_Narrative == null)
						Tag70C_Narrative = new List<string>();
					Tag70C_Narrative.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "20C") && (i <= 5))
				{
					Tag20C_Reference = tag.Value;
					i = 5;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 6))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 6;
				}
			}
        }
        
        public static List<MT515_SequenceE> GetMT515_SequenceEList(SwiftTagList tags)
        {
			List<MT515_SequenceE> result = new List<MT515_SequenceE>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT515_SequenceE.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceE.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT515_SequenceE.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceE.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT515_SequenceE sequence = new MT515_SequenceE(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Repo Details
    /// <summary>
    public partial class MT515_SequenceF
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "REPO";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Closing Date/Time
        /// <summary>
		public List<string> Tag98A_Date { get; set; }
        /// <summary>
        /// Closing Date/Time
        /// <summary>
		public List<string> Tag98B_DateCode { get; set; }
        /// <summary>
        /// Closing Date/Time
        /// <summary>
		public List<string> Tag98C_DateTime { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public List<string> Tag20C_Reference { get; set; }
        /// <summary>
        /// Rate
        /// <summary>
		public List<string> Tag92C_Rate { get; set; }
        /// <summary>
        /// Rate
        /// <summary>
		public List<string> Tag92A_Rate { get; set; }
        /// <summary>
        /// Number Count
        /// <summary>
		public List<string> Tag99B_NumberCount { get; set; }
        /// <summary>
        /// Amount
        /// <summary>
		public List<string> Tag19A_Amount { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public string Tag70C_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "REPO";
        /// <summary>
        /// End Of BLock
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT515_SequenceF()
        {
        }
        
        public MT515_SequenceF(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag98A_Date != null)
				tags.AddRange(Tag98A_Date.Select(x => new SwiftTag("98A", x)).ToList());
			if (Tag98B_DateCode != null)
				tags.AddRange(Tag98B_DateCode.Select(x => new SwiftTag("98B", x)).ToList());
			if (Tag98C_DateTime != null)
				tags.AddRange(Tag98C_DateTime.Select(x => new SwiftTag("98C", x)).ToList());
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (Tag20C_Reference != null)
				tags.AddRange(Tag20C_Reference.Select(x => new SwiftTag("20C", x)).ToList());
			if (Tag92C_Rate != null)
				tags.AddRange(Tag92C_Rate.Select(x => new SwiftTag("92C", x)).ToList());
			if (Tag92A_Rate != null)
				tags.AddRange(Tag92A_Rate.Select(x => new SwiftTag("92A", x)).ToList());
			if (Tag99B_NumberCount != null)
				tags.AddRange(Tag99B_NumberCount.Select(x => new SwiftTag("99B", x)).ToList());
			if (Tag19A_Amount != null)
				tags.AddRange(Tag19A_Amount.Select(x => new SwiftTag("19A", x)).ToList());
			if (Tag70C_Narrative != null)
				tags.Add(new SwiftTag("70C", Tag70C_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "98A") && (i <= 2))
				{
					if (Tag98A_Date == null)
						Tag98A_Date = new List<string>();
					Tag98A_Date.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "98B") && (i <= 2))
				{
					if (Tag98B_DateCode == null)
						Tag98B_DateCode = new List<string>();
					Tag98B_DateCode.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "98C") && (i <= 2))
				{
					if (Tag98C_DateTime == null)
						Tag98C_DateTime = new List<string>();
					Tag98C_DateTime.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "22F") && (i <= 3))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "20C") && (i <= 4))
				{
					if (Tag20C_Reference == null)
						Tag20C_Reference = new List<string>();
					Tag20C_Reference.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "92C") && (i <= 5))
				{
					if (Tag92C_Rate == null)
						Tag92C_Rate = new List<string>();
					Tag92C_Rate.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "92A") && (i <= 5))
				{
					if (Tag92A_Rate == null)
						Tag92A_Rate = new List<string>();
					Tag92A_Rate.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "99B") && (i <= 6))
				{
					if (Tag99B_NumberCount == null)
						Tag99B_NumberCount = new List<string>();
					Tag99B_NumberCount.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "19A") && (i <= 7))
				{
					if (Tag19A_Amount == null)
						Tag19A_Amount = new List<string>();
					Tag19A_Amount.Add(tag.Value);
					i = 7;
				}
				else if ((tag.Name == "70C") && (i <= 8))
				{
					Tag70C_Narrative = tag.Value;
					i = 8;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 9))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 9;
				}
			}
        }
        
        public static MT515_SequenceF GetMT515_SequenceF(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT515_SequenceF.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT515_SequenceF.Tag16S_EndOfBlock_Value));
			return new MT515_SequenceF(subBlock);
        }
    }
}
