//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swift.Net.Mt.Category5
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// MT524 (SRG 2019)
    /// <summary>
    public partial class MT524 : SwiftMessage
    {
        
		public override SwiftBlock4 Block4 { get => new SwiftBlock4(GetBlock4Tags()); set => SetBlock4Tags(value); }

        /// <summary>
        /// Mandatory Sequence A General Information
        /// <summary>
		public MT524_SequenceA SequenceA { get; set; }
        /// <summary>
        /// Mandatory Sequence B Intra-Position Details
        /// <summary>
		public MT524_SequenceB SequenceB { get; set; }
        /// <summary>
        /// Optional Sequence C Additional Information
        /// <summary>
		public MT524_SequenceC SequenceC { get; set; }
        
        public MT524()
        {
        }
        
        public MT524(SwiftTagList tags)
        {
			SetBlock4Tags(tags);
        }
        
        public virtual SwiftTagList GetBlock4Tags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (SequenceA != null)
				tags.AddRange(SequenceA.GetTags());
			if (SequenceB != null)
				tags.AddRange(SequenceB.GetTags());
			if (SequenceC != null)
				tags.AddRange(SequenceC.GetTags());
			return tags;
        }
        
        public virtual void SetBlock4Tags(SwiftTagList tags)
        {
			SequenceA = MT524_SequenceA.GetMT524_SequenceA(tags);
			SequenceB = MT524_SequenceB.GetMT524_SequenceB(tags);
			SequenceC = MT524_SequenceC.GetMT524_SequenceC(tags);
        }
        
        public static MT524 Parse(string message)
        {
			SwiftMessage swiftMessage = new SwiftParser().GetSwiftMessage(message);
			MT524 result = new MT524()
			{
				Block1 = swiftMessage.Block1,
				Block2 = swiftMessage.Block2,
				Block3 = swiftMessage.Block3,
				Block4 = swiftMessage.Block4,
				Block5 = swiftMessage.Block5,
			};
			return result;
        }
        
        public static string Write(MT524 message)
        {
			return new SwiftWriter().GetFinMessage(message);
        }
    }
    
    /// <summary>
    /// Mandatory Sequence A General Information
    /// <summary>
    public partial class MT524_SequenceA
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "GENL";
        /// <summary>
        /// Start of block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Sender's Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
        /// <summary>
        /// Function of the Message
        /// <summary>
		public string Tag23G_FunctionOfTheMessage { get; set; }
        /// <summary>
        /// Preparation Date/Time
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Preparation Date/Time
        /// <summary>
		public string Tag98C_DateTime { get; set; }
        /// <summary>
        /// Trade Date/Time
        /// <summary>
		public string Tag98E_DateTime { get; set; }
        /// <summary>
        /// Number Count
        /// <summary>
		public List<string> Tag99B_NumberCount { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public string Tag22F_Indicator { get; set; }
        /// <summary>
        /// Optional Subsequence A1 Linkages
        /// <summary>
		public MT524_SequenceA1 SequenceA1 { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "GENL";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT524_SequenceA()
        {
        }
        
        public MT524_SequenceA(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag23G_FunctionOfTheMessage != null)
				tags.Add(new SwiftTag("23G", Tag23G_FunctionOfTheMessage));
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98C_DateTime != null)
				tags.Add(new SwiftTag("98C", Tag98C_DateTime));
			if (Tag98E_DateTime != null)
				tags.Add(new SwiftTag("98E", Tag98E_DateTime));
			if (Tag99B_NumberCount != null)
				tags.AddRange(Tag99B_NumberCount.Select(x => new SwiftTag("99B", x)).ToList());
			if (Tag22F_Indicator != null)
				tags.Add(new SwiftTag("22F", Tag22F_Indicator));
			if (SequenceA1 != null)
				tags.AddRange(SequenceA1.GetTags());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "20C") && (i <= 2))
				{
					Tag20C_Reference = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "23G") && (i <= 3))
				{
					Tag23G_FunctionOfTheMessage = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "98A") && (i <= 4))
				{
					Tag98A_Date = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "98C") && (i <= 4))
				{
					Tag98C_DateTime = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "98E") && (i <= 4))
				{
					Tag98E_DateTime = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "99B") && (i <= 5))
				{
					if (Tag99B_NumberCount == null)
						Tag99B_NumberCount = new List<string>();
					Tag99B_NumberCount.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "22F") && (i <= 6))
				{
					Tag22F_Indicator = tag.Value;
					i = 6;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 7))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 7;
				}
			}
			SequenceA1 = MT524_SequenceA1.GetMT524_SequenceA1(tags);
        }
        
        public static MT524_SequenceA GetMT524_SequenceA(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT524_SequenceA.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT524_SequenceA.Tag16S_EndOfBlock_Value));
			return new MT524_SequenceA(subBlock);
        }
    }
    
    /// <summary>
    /// Optional Subsequence A1 Linkages
    /// <summary>
    public partial class MT524_SequenceA1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "LINK";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Linkage Type Indicator
        /// <summary>
		public string Tag22F_Indicator { get; set; }
        /// <summary>
        /// Number Identification
        /// <summary>
		public string Tag13A_NumberIdentification { get; set; }
        /// <summary>
        /// Number Identification
        /// <summary>
		public string Tag13B_NumberIdentification { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "LINK";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT524_SequenceA1()
        {
        }
        
        public MT524_SequenceA1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag22F_Indicator != null)
				tags.Add(new SwiftTag("22F", Tag22F_Indicator));
			if (Tag13A_NumberIdentification != null)
				tags.Add(new SwiftTag("13A", Tag13A_NumberIdentification));
			if (Tag13B_NumberIdentification != null)
				tags.Add(new SwiftTag("13B", Tag13B_NumberIdentification));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "22F") && (i <= 2))
				{
					Tag22F_Indicator = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "13A") && (i <= 3))
				{
					Tag13A_NumberIdentification = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "13B") && (i <= 3))
				{
					Tag13B_NumberIdentification = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "20C") && (i <= 4))
				{
					Tag20C_Reference = tag.Value;
					i = 4;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 5))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 5;
				}
			}
        }
        
        public static MT524_SequenceA1 GetMT524_SequenceA1(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT524_SequenceA1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT524_SequenceA1.Tag16S_EndOfBlock_Value));
			return new MT524_SequenceA1(subBlock);
        }
    }
    
    /// <summary>
    /// Mandatory Sequence B Intra-Position Details
    /// <summary>
    public partial class MT524_SequenceB
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "INPOSDET";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Account Owner
        /// <summary>
		public string Tag95P_Party { get; set; }
        /// <summary>
        /// Account Owner
        /// <summary>
		public string Tag95R_Party { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public string Tag97A_Account { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public string Tag97B_Account { get; set; }
        /// <summary>
        /// Place of Safekeeping
        /// <summary>
		public string Tag94B_Place { get; set; }
        /// <summary>
        /// Place of Safekeeping
        /// <summary>
		public string Tag94C_Place { get; set; }
        /// <summary>
        /// Place of Safekeeping
        /// <summary>
		public string Tag94F_Place { get; set; }
        /// <summary>
        /// Quantity of Financial Instrument to be Settled
        /// <summary>
		public string Tag36B_QuantityOfFinancialInstrument { get; set; }
        /// <summary>
        /// Number Identification
        /// <summary>
		public string Tag13B_NumberIdentification { get; set; }
        /// <summary>
        /// Identification Of Financial Instrument
        /// <summary>
		public string Tag35B_IdentificationOfFinancialInstrument { get; set; }
        /// <summary>
        /// Financial Instrument Attributes
        /// <summary>
		public MT524_SequenceB1 SequenceB1 { get; set; }
        /// <summary>
        /// Settlement Date/Time
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Settlement Date/Time
        /// <summary>
		public string Tag98C_DateTime { get; set; }
        /// <summary>
        /// Settlement Instruction Processing Narrative
        /// <summary>
		public string Tag70E_Narrative { get; set; }
        /// <summary>
        /// Balance
        /// <summary>
		public List<string> Tag93A_Balance { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "INPOSDET";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT524_SequenceB()
        {
        }
        
        public MT524_SequenceB(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95P_Party != null)
				tags.Add(new SwiftTag("95P", Tag95P_Party));
			if (Tag95R_Party != null)
				tags.Add(new SwiftTag("95R", Tag95R_Party));
			if (Tag97A_Account != null)
				tags.Add(new SwiftTag("97A", Tag97A_Account));
			if (Tag97B_Account != null)
				tags.Add(new SwiftTag("97B", Tag97B_Account));
			if (Tag94B_Place != null)
				tags.Add(new SwiftTag("94B", Tag94B_Place));
			if (Tag94C_Place != null)
				tags.Add(new SwiftTag("94C", Tag94C_Place));
			if (Tag94F_Place != null)
				tags.Add(new SwiftTag("94F", Tag94F_Place));
			if (Tag36B_QuantityOfFinancialInstrument != null)
				tags.Add(new SwiftTag("36B", Tag36B_QuantityOfFinancialInstrument));
			if (Tag13B_NumberIdentification != null)
				tags.Add(new SwiftTag("13B", Tag13B_NumberIdentification));
			if (Tag35B_IdentificationOfFinancialInstrument != null)
				tags.Add(new SwiftTag("35B", Tag35B_IdentificationOfFinancialInstrument));
			if (SequenceB1 != null)
				tags.AddRange(SequenceB1.GetTags());
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98C_DateTime != null)
				tags.Add(new SwiftTag("98C", Tag98C_DateTime));
			if (Tag70E_Narrative != null)
				tags.Add(new SwiftTag("70E", Tag70E_Narrative));
			if (Tag93A_Balance != null)
				tags.AddRange(Tag93A_Balance.Select(x => new SwiftTag("93A", x)).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					Tag95P_Party = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					Tag95R_Party = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "97A") && (i <= 3))
				{
					Tag97A_Account = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "97B") && (i <= 3))
				{
					Tag97B_Account = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "94B") && (i <= 4))
				{
					Tag94B_Place = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "94C") && (i <= 4))
				{
					Tag94C_Place = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "94F") && (i <= 4))
				{
					Tag94F_Place = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "36B") && (i <= 5))
				{
					Tag36B_QuantityOfFinancialInstrument = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "13B") && (i <= 6))
				{
					Tag13B_NumberIdentification = tag.Value;
					i = 6;
				}
				else if ((tag.Name == "35B") && (i <= 7))
				{
					Tag35B_IdentificationOfFinancialInstrument = tag.Value;
					i = 7;
				}
				else if ((tag.Name == "98A") && (i <= 8))
				{
					Tag98A_Date = tag.Value;
					i = 8;
				}
				else if ((tag.Name == "98C") && (i <= 8))
				{
					Tag98C_DateTime = tag.Value;
					i = 8;
				}
				else if ((tag.Name == "70E") && (i <= 9))
				{
					Tag70E_Narrative = tag.Value;
					i = 9;
				}
				else if ((tag.Name == "93A") && (i <= 10))
				{
					if (Tag93A_Balance == null)
						Tag93A_Balance = new List<string>();
					Tag93A_Balance.Add(tag.Value);
					i = 10;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 11))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 11;
				}
			}
			SequenceB1 = MT524_SequenceB1.GetMT524_SequenceB1(tags);
        }
        
        public static MT524_SequenceB GetMT524_SequenceB(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT524_SequenceB.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT524_SequenceB.Tag16S_EndOfBlock_Value));
			return new MT524_SequenceB(subBlock);
        }
    }
    
    /// <summary>
    /// Financial Instrument Attributes
    /// <summary>
    public partial class MT524_SequenceB1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "FIA";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Place of Trade
        /// <summary>
		public string Tag94B_Place { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Type of Financial Instrument
        /// <summary>
		public List<string> Tag12A_TypeOfFinancialInstrument { get; set; }
        /// <summary>
        /// Type of Financial Instrument
        /// <summary>
		public List<string> Tag12C_TypeOfFinancialInstrument { get; set; }
        /// <summary>
        /// Type of Financial Instrument
        /// <summary>
		public List<string> Tag12B_TypeOfFinancialInstrument { get; set; }
        /// <summary>
        /// Currency Of Denomination
        /// <summary>
		public string Tag11A_CurrencyOfDenomination { get; set; }
        /// <summary>
        /// Date
        /// <summary>
		public List<string> Tag98A_Date { get; set; }
        /// <summary>
        /// Rate
        /// <summary>
		public List<string> Tag92A_Rate { get; set; }
        /// <summary>
        /// Number Identification
        /// <summary>
		public List<string> Tag13A_NumberIdentification { get; set; }
        /// <summary>
        /// Number Identification
        /// <summary>
		public List<string> Tag13B_NumberIdentification { get; set; }
        /// <summary>
        /// Number Identification
        /// <summary>
		public List<string> Tag13K_NumberIdentification { get; set; }
        /// <summary>
        /// Flag
        /// <summary>
		public List<string> Tag17B_Flag { get; set; }
        /// <summary>
        /// Price
        /// <summary>
		public List<string> Tag90A_Price { get; set; }
        /// <summary>
        /// Deal Price
        /// <summary>
		public List<string> Tag90B_Price { get; set; }
        /// <summary>
        /// Quantity Of Financial Instrument
        /// <summary>
		public List<string> Tag36B_QuantityOfFinancialInstrument { get; set; }
        /// <summary>
        /// Identification Of Financial Instrument
        /// <summary>
		public List<string> Tag35B_IdentificationOfFinancialInstrument { get; set; }
        /// <summary>
        /// Financial Instrument Attribute Narrative
        /// <summary>
		public string Tag70E_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "FIA";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT524_SequenceB1()
        {
        }
        
        public MT524_SequenceB1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag94B_Place != null)
				tags.Add(new SwiftTag("94B", Tag94B_Place));
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (Tag12A_TypeOfFinancialInstrument != null)
				tags.AddRange(Tag12A_TypeOfFinancialInstrument.Select(x => new SwiftTag("12A", x)).ToList());
			if (Tag12C_TypeOfFinancialInstrument != null)
				tags.AddRange(Tag12C_TypeOfFinancialInstrument.Select(x => new SwiftTag("12C", x)).ToList());
			if (Tag12B_TypeOfFinancialInstrument != null)
				tags.AddRange(Tag12B_TypeOfFinancialInstrument.Select(x => new SwiftTag("12B", x)).ToList());
			if (Tag11A_CurrencyOfDenomination != null)
				tags.Add(new SwiftTag("11A", Tag11A_CurrencyOfDenomination));
			if (Tag98A_Date != null)
				tags.AddRange(Tag98A_Date.Select(x => new SwiftTag("98A", x)).ToList());
			if (Tag92A_Rate != null)
				tags.AddRange(Tag92A_Rate.Select(x => new SwiftTag("92A", x)).ToList());
			if (Tag13A_NumberIdentification != null)
				tags.AddRange(Tag13A_NumberIdentification.Select(x => new SwiftTag("13A", x)).ToList());
			if (Tag13B_NumberIdentification != null)
				tags.AddRange(Tag13B_NumberIdentification.Select(x => new SwiftTag("13B", x)).ToList());
			if (Tag13K_NumberIdentification != null)
				tags.AddRange(Tag13K_NumberIdentification.Select(x => new SwiftTag("13K", x)).ToList());
			if (Tag17B_Flag != null)
				tags.AddRange(Tag17B_Flag.Select(x => new SwiftTag("17B", x)).ToList());
			if (Tag90A_Price != null)
				tags.AddRange(Tag90A_Price.Select(x => new SwiftTag("90A", x)).ToList());
			if (Tag90B_Price != null)
				tags.AddRange(Tag90B_Price.Select(x => new SwiftTag("90B", x)).ToList());
			if (Tag36B_QuantityOfFinancialInstrument != null)
				tags.AddRange(Tag36B_QuantityOfFinancialInstrument.Select(x => new SwiftTag("36B", x)).ToList());
			if (Tag35B_IdentificationOfFinancialInstrument != null)
				tags.AddRange(Tag35B_IdentificationOfFinancialInstrument.Select(x => new SwiftTag("35B", x)).ToList());
			if (Tag70E_Narrative != null)
				tags.Add(new SwiftTag("70E", Tag70E_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "94B") && (i <= 2))
				{
					Tag94B_Place = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "22F") && (i <= 3))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "12A") && (i <= 4))
				{
					if (Tag12A_TypeOfFinancialInstrument == null)
						Tag12A_TypeOfFinancialInstrument = new List<string>();
					Tag12A_TypeOfFinancialInstrument.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "12C") && (i <= 4))
				{
					if (Tag12C_TypeOfFinancialInstrument == null)
						Tag12C_TypeOfFinancialInstrument = new List<string>();
					Tag12C_TypeOfFinancialInstrument.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "12B") && (i <= 4))
				{
					if (Tag12B_TypeOfFinancialInstrument == null)
						Tag12B_TypeOfFinancialInstrument = new List<string>();
					Tag12B_TypeOfFinancialInstrument.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "11A") && (i <= 5))
				{
					Tag11A_CurrencyOfDenomination = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "98A") && (i <= 6))
				{
					if (Tag98A_Date == null)
						Tag98A_Date = new List<string>();
					Tag98A_Date.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "92A") && (i <= 7))
				{
					if (Tag92A_Rate == null)
						Tag92A_Rate = new List<string>();
					Tag92A_Rate.Add(tag.Value);
					i = 7;
				}
				else if ((tag.Name == "13A") && (i <= 8))
				{
					if (Tag13A_NumberIdentification == null)
						Tag13A_NumberIdentification = new List<string>();
					Tag13A_NumberIdentification.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "13B") && (i <= 8))
				{
					if (Tag13B_NumberIdentification == null)
						Tag13B_NumberIdentification = new List<string>();
					Tag13B_NumberIdentification.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "13K") && (i <= 8))
				{
					if (Tag13K_NumberIdentification == null)
						Tag13K_NumberIdentification = new List<string>();
					Tag13K_NumberIdentification.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "17B") && (i <= 9))
				{
					if (Tag17B_Flag == null)
						Tag17B_Flag = new List<string>();
					Tag17B_Flag.Add(tag.Value);
					i = 9;
				}
				else if ((tag.Name == "90A") && (i <= 10))
				{
					if (Tag90A_Price == null)
						Tag90A_Price = new List<string>();
					Tag90A_Price.Add(tag.Value);
					i = 10;
				}
				else if ((tag.Name == "90B") && (i <= 10))
				{
					if (Tag90B_Price == null)
						Tag90B_Price = new List<string>();
					Tag90B_Price.Add(tag.Value);
					i = 10;
				}
				else if ((tag.Name == "36B") && (i <= 11))
				{
					if (Tag36B_QuantityOfFinancialInstrument == null)
						Tag36B_QuantityOfFinancialInstrument = new List<string>();
					Tag36B_QuantityOfFinancialInstrument.Add(tag.Value);
					i = 11;
				}
				else if ((tag.Name == "35B") && (i <= 12))
				{
					if (Tag35B_IdentificationOfFinancialInstrument == null)
						Tag35B_IdentificationOfFinancialInstrument = new List<string>();
					Tag35B_IdentificationOfFinancialInstrument.Add(tag.Value);
					i = 12;
				}
				else if ((tag.Name == "70E") && (i <= 13))
				{
					Tag70E_Narrative = tag.Value;
					i = 13;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 14))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 14;
				}
			}
        }
        
        public static MT524_SequenceB1 GetMT524_SequenceB1(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT524_SequenceB1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT524_SequenceB1.Tag16S_EndOfBlock_Value));
			return new MT524_SequenceB1(subBlock);
        }
    }
    
    /// <summary>
    /// Optional Sequence C Additional Information
    /// <summary>
    public partial class MT524_SequenceC
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "ADDINFO";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "ADDINFO";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT524_SequenceC()
        {
        }
        
        public MT524_SequenceC(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 3))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 3;
				}
			}
        }
        
        public static MT524_SequenceC GetMT524_SequenceC(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT524_SequenceC.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT524_SequenceC.Tag16S_EndOfBlock_Value));
			return new MT524_SequenceC(subBlock);
        }
    }
}
