//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swift.Net.Mt.Category5
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// MT548 (SRG 2019)
    /// <summary>
    public partial class MT548 : SwiftMessage
    {
        
		public override SwiftBlock4 Block4 { get => new SwiftBlock4(GetBlock4Tags()); set => SetBlock4Tags(value); }

        /// <summary>
        /// General Information
        /// <summary>
		public MT548_SequenceA SequenceA { get; set; }
        /// <summary>
        /// Settlement Transaction Details
        /// <summary>
		public MT548_SequenceB SequenceB { get; set; }
        /// <summary>
        /// Penalties
        /// <summary>
		public MT548_SequenceC SequenceC { get; set; }
        /// <summary>
        /// Additional Information
        /// <summary>
		public List<MT548_SequenceD> SequenceDList { get; set; }
        
        public MT548()
        {
        }
        
        public MT548(SwiftTagList tags)
        {
			SetBlock4Tags(tags);
        }
        
        public virtual SwiftTagList GetBlock4Tags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (SequenceA != null)
				tags.AddRange(SequenceA.GetTags());
			if (SequenceB != null)
				tags.AddRange(SequenceB.GetTags());
			if (SequenceC != null)
				tags.AddRange(SequenceC.GetTags());
			if (SequenceDList != null)
				tags.AddRange(SequenceDList.SelectMany(x => x.GetTags()).ToList());
			return tags;
        }
        
        public virtual void SetBlock4Tags(SwiftTagList tags)
        {
			SequenceA = MT548_SequenceA.GetMT548_SequenceA(tags);
			SequenceB = MT548_SequenceB.GetMT548_SequenceB(tags);
			SequenceC = MT548_SequenceC.GetMT548_SequenceC(tags);
			SequenceDList = MT548_SequenceD.GetMT548_SequenceDList(tags);
        }
        
        public static MT548 Parse(string message)
        {
			SwiftMessage swiftMessage = new SwiftParser().GetSwiftMessage(message);
			MT548 result = new MT548()
			{
				Block1 = swiftMessage.Block1,
				Block2 = swiftMessage.Block2,
				Block3 = swiftMessage.Block3,
				Block4 = swiftMessage.Block4,
				Block5 = swiftMessage.Block5,
			};
			return result;
        }
        
        public static string Write(MT548 message)
        {
			return new SwiftWriter().GetFinMessage(message);
        }
    }
    
    /// <summary>
    /// General Information
    /// <summary>
    public partial class MT548_SequenceA
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "GENL";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Sender's Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
        /// <summary>
        /// Function of the Message
        /// <summary>
		public string Tag23G_FunctionOfTheMessage { get; set; }
        /// <summary>
        /// Preparation Date
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Preparation Date/Time
        /// <summary>
		public string Tag98C_DateTime { get; set; }
        /// <summary>
        /// Preparation Date/Time
        /// <summary>
		public string Tag98E_DateTime { get; set; }
        /// <summary>
        /// Linkages
        /// <summary>
		public List<MT548_SequenceA1> SequenceA1List { get; set; }
        /// <summary>
        /// Status
        /// <summary>
		public List<MT548_SequenceA2> SequenceA2List { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "GENL";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceA()
        {
        }
        
        public MT548_SequenceA(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag23G_FunctionOfTheMessage != null)
				tags.Add(new SwiftTag("23G", Tag23G_FunctionOfTheMessage));
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98C_DateTime != null)
				tags.Add(new SwiftTag("98C", Tag98C_DateTime));
			if (Tag98E_DateTime != null)
				tags.Add(new SwiftTag("98E", Tag98E_DateTime));
			if (SequenceA1List != null)
				tags.AddRange(SequenceA1List.SelectMany(x => x.GetTags()).ToList());
			if (SequenceA2List != null)
				tags.AddRange(SequenceA2List.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "20C") && (i <= 2))
				{
					Tag20C_Reference = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "23G") && (i <= 3))
				{
					Tag23G_FunctionOfTheMessage = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "98A") && (i <= 4))
				{
					Tag98A_Date = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "98C") && (i <= 4))
				{
					Tag98C_DateTime = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "98E") && (i <= 4))
				{
					Tag98E_DateTime = tag.Value;
					i = 4;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 5))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 5;
				}
			}
			SequenceA1List = MT548_SequenceA1.GetMT548_SequenceA1List(tags);
			SequenceA2List = MT548_SequenceA2.GetMT548_SequenceA2List(tags);
        }
        
        public static MT548_SequenceA GetMT548_SequenceA(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT548_SequenceA.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceA.Tag16S_EndOfBlock_Value));
			return new MT548_SequenceA(subBlock);
        }
    }
    
    /// <summary>
    /// Linkages
    /// <summary>
    public partial class MT548_SequenceA1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "LINK";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Linked Message
        /// <summary>
		public string Tag13A_NumberIdentification { get; set; }
        /// <summary>
        /// Linked Message
        /// <summary>
		public string Tag13B_NumberIdentification { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public string Tag20U_Reference { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "LINK";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceA1()
        {
        }
        
        public MT548_SequenceA1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag13A_NumberIdentification != null)
				tags.Add(new SwiftTag("13A", Tag13A_NumberIdentification));
			if (Tag13B_NumberIdentification != null)
				tags.Add(new SwiftTag("13B", Tag13B_NumberIdentification));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag20U_Reference != null)
				tags.Add(new SwiftTag("20U", Tag20U_Reference));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "13A") && (i <= 2))
				{
					Tag13A_NumberIdentification = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "13B") && (i <= 2))
				{
					Tag13B_NumberIdentification = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "20C") && (i <= 3))
				{
					Tag20C_Reference = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "20U") && (i <= 3))
				{
					Tag20U_Reference = tag.Value;
					i = 3;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 4))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 4;
				}
			}
        }
        
        public static List<MT548_SequenceA1> GetMT548_SequenceA1List(SwiftTagList tags)
        {
			List<MT548_SequenceA1> result = new List<MT548_SequenceA1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT548_SequenceA1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceA1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT548_SequenceA1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceA1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT548_SequenceA1 sequence = new MT548_SequenceA1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Status
    /// <summary>
    public partial class MT548_SequenceA2
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "STAT";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Status
        /// <summary>
		public string Tag25D_Status { get; set; }
        /// <summary>
        /// Reason
        /// <summary>
		public List<MT548_SequenceA2a> SequenceA2aList { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "STAT";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceA2()
        {
        }
        
        public MT548_SequenceA2(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag25D_Status != null)
				tags.Add(new SwiftTag("25D", Tag25D_Status));
			if (SequenceA2aList != null)
				tags.AddRange(SequenceA2aList.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "25D") && (i <= 2))
				{
					Tag25D_Status = tag.Value;
					i = 2;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 3))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 3;
				}
			}
			SequenceA2aList = MT548_SequenceA2a.GetMT548_SequenceA2aList(tags);
        }
        
        public static List<MT548_SequenceA2> GetMT548_SequenceA2List(SwiftTagList tags)
        {
			List<MT548_SequenceA2> result = new List<MT548_SequenceA2>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT548_SequenceA2.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceA2.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT548_SequenceA2.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceA2.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT548_SequenceA2 sequence = new MT548_SequenceA2(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Reason
    /// <summary>
    public partial class MT548_SequenceA2a
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "REAS";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Reason
        /// <summary>
		public string Tag24B_Reason { get; set; }
        /// <summary>
        /// Reason Narrative
        /// <summary>
		public string Tag70D_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "REAS";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceA2a()
        {
        }
        
        public MT548_SequenceA2a(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag24B_Reason != null)
				tags.Add(new SwiftTag("24B", Tag24B_Reason));
			if (Tag70D_Narrative != null)
				tags.Add(new SwiftTag("70D", Tag70D_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "24B") && (i <= 2))
				{
					Tag24B_Reason = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "70D") && (i <= 3))
				{
					Tag70D_Narrative = tag.Value;
					i = 3;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 4))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 4;
				}
			}
        }
        
        public static List<MT548_SequenceA2a> GetMT548_SequenceA2aList(SwiftTagList tags)
        {
			List<MT548_SequenceA2a> result = new List<MT548_SequenceA2a>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT548_SequenceA2a.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceA2a.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT548_SequenceA2a.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceA2a.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT548_SequenceA2a sequence = new MT548_SequenceA2a(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Settlement Transaction Details
    /// <summary>
    public partial class MT548_SequenceB
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "SETTRAN";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Place
        /// <summary>
		public List<string> Tag94B_Place { get; set; }
        /// <summary>
        /// Place
        /// <summary>
		public List<string> Tag94C_Place { get; set; }
        /// <summary>
        /// Place
        /// <summary>
		public List<string> Tag94F_Place { get; set; }
        /// <summary>
        /// Place
        /// <summary>
		public List<string> Tag94H_Place { get; set; }
        /// <summary>
        /// Place
        /// <summary>
		public List<string> Tag94L_Place { get; set; }
        /// <summary>
        /// Identification of the Financial Instrument
        /// <summary>
		public string Tag35B_IdentificationOfFinancialInstrument { get; set; }
        /// <summary>
        /// Quantity of Financial Instrument to be Settled
        /// <summary>
		public List<string> Tag36B_QuantityOfFinancialInstrument { get; set; }
        /// <summary>
        /// Amount
        /// <summary>
		public List<string> Tag19A_Amount { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95L_Party { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public string Tag97A_Account { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public string Tag97B_Account { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22H_Indicator { get; set; }
        /// <summary>
        /// Date
        /// <summary>
		public List<string> Tag98A_Date { get; set; }
        /// <summary>
        /// Date Code
        /// <summary>
		public List<string> Tag98B_DateCode { get; set; }
        /// <summary>
        /// Date/Time
        /// <summary>
		public List<string> Tag98C_DateTime { get; set; }
        /// <summary>
        /// Trade Date/Time
        /// <summary>
		public List<string> Tag98E_DateTime { get; set; }
        /// <summary>
        /// Settlement Instruction Processing Narrative
        /// <summary>
		public string Tag70E_Narrative { get; set; }
        /// <summary>
        /// Settlement Parties
        /// <summary>
		public List<MT548_SequenceB1> SequenceB1List { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "SETTRAN";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceB()
        {
        }
        
        public MT548_SequenceB(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag94B_Place != null)
				tags.AddRange(Tag94B_Place.Select(x => new SwiftTag("94B", x)).ToList());
			if (Tag94C_Place != null)
				tags.AddRange(Tag94C_Place.Select(x => new SwiftTag("94C", x)).ToList());
			if (Tag94F_Place != null)
				tags.AddRange(Tag94F_Place.Select(x => new SwiftTag("94F", x)).ToList());
			if (Tag94H_Place != null)
				tags.AddRange(Tag94H_Place.Select(x => new SwiftTag("94H", x)).ToList());
			if (Tag94L_Place != null)
				tags.AddRange(Tag94L_Place.Select(x => new SwiftTag("94L", x)).ToList());
			if (Tag35B_IdentificationOfFinancialInstrument != null)
				tags.Add(new SwiftTag("35B", Tag35B_IdentificationOfFinancialInstrument));
			if (Tag36B_QuantityOfFinancialInstrument != null)
				tags.AddRange(Tag36B_QuantityOfFinancialInstrument.Select(x => new SwiftTag("36B", x)).ToList());
			if (Tag19A_Amount != null)
				tags.AddRange(Tag19A_Amount.Select(x => new SwiftTag("19A", x)).ToList());
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95L_Party != null)
				tags.AddRange(Tag95L_Party.Select(x => new SwiftTag("95L", x)).ToList());
			if (Tag97A_Account != null)
				tags.Add(new SwiftTag("97A", Tag97A_Account));
			if (Tag97B_Account != null)
				tags.Add(new SwiftTag("97B", Tag97B_Account));
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (Tag22H_Indicator != null)
				tags.AddRange(Tag22H_Indicator.Select(x => new SwiftTag("22H", x)).ToList());
			if (Tag98A_Date != null)
				tags.AddRange(Tag98A_Date.Select(x => new SwiftTag("98A", x)).ToList());
			if (Tag98B_DateCode != null)
				tags.AddRange(Tag98B_DateCode.Select(x => new SwiftTag("98B", x)).ToList());
			if (Tag98C_DateTime != null)
				tags.AddRange(Tag98C_DateTime.Select(x => new SwiftTag("98C", x)).ToList());
			if (Tag98E_DateTime != null)
				tags.AddRange(Tag98E_DateTime.Select(x => new SwiftTag("98E", x)).ToList());
			if (Tag70E_Narrative != null)
				tags.Add(new SwiftTag("70E", Tag70E_Narrative));
			if (SequenceB1List != null)
				tags.AddRange(SequenceB1List.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "94B") && (i <= 2))
				{
					if (Tag94B_Place == null)
						Tag94B_Place = new List<string>();
					Tag94B_Place.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "94C") && (i <= 2))
				{
					if (Tag94C_Place == null)
						Tag94C_Place = new List<string>();
					Tag94C_Place.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "94F") && (i <= 2))
				{
					if (Tag94F_Place == null)
						Tag94F_Place = new List<string>();
					Tag94F_Place.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "94H") && (i <= 2))
				{
					if (Tag94H_Place == null)
						Tag94H_Place = new List<string>();
					Tag94H_Place.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "94L") && (i <= 2))
				{
					if (Tag94L_Place == null)
						Tag94L_Place = new List<string>();
					Tag94L_Place.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "35B") && (i <= 3))
				{
					Tag35B_IdentificationOfFinancialInstrument = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "36B") && (i <= 4))
				{
					if (Tag36B_QuantityOfFinancialInstrument == null)
						Tag36B_QuantityOfFinancialInstrument = new List<string>();
					Tag36B_QuantityOfFinancialInstrument.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "19A") && (i <= 5))
				{
					if (Tag19A_Amount == null)
						Tag19A_Amount = new List<string>();
					Tag19A_Amount.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "95P") && (i <= 6))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "95R") && (i <= 6))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "95L") && (i <= 6))
				{
					if (Tag95L_Party == null)
						Tag95L_Party = new List<string>();
					Tag95L_Party.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "97A") && (i <= 7))
				{
					Tag97A_Account = tag.Value;
					i = 7;
				}
				else if ((tag.Name == "97B") && (i <= 7))
				{
					Tag97B_Account = tag.Value;
					i = 7;
				}
				else if ((tag.Name == "22F") && (i <= 8))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "22H") && (i <= 8))
				{
					if (Tag22H_Indicator == null)
						Tag22H_Indicator = new List<string>();
					Tag22H_Indicator.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "98A") && (i <= 9))
				{
					if (Tag98A_Date == null)
						Tag98A_Date = new List<string>();
					Tag98A_Date.Add(tag.Value);
					i = 9;
				}
				else if ((tag.Name == "98B") && (i <= 9))
				{
					if (Tag98B_DateCode == null)
						Tag98B_DateCode = new List<string>();
					Tag98B_DateCode.Add(tag.Value);
					i = 9;
				}
				else if ((tag.Name == "98C") && (i <= 9))
				{
					if (Tag98C_DateTime == null)
						Tag98C_DateTime = new List<string>();
					Tag98C_DateTime.Add(tag.Value);
					i = 9;
				}
				else if ((tag.Name == "98E") && (i <= 9))
				{
					if (Tag98E_DateTime == null)
						Tag98E_DateTime = new List<string>();
					Tag98E_DateTime.Add(tag.Value);
					i = 9;
				}
				else if ((tag.Name == "70E") && (i <= 10))
				{
					Tag70E_Narrative = tag.Value;
					i = 10;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 11))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 11;
				}
			}
			SequenceB1List = MT548_SequenceB1.GetMT548_SequenceB1List(tags);
        }
        
        public static MT548_SequenceB GetMT548_SequenceB(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT548_SequenceB.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceB.Tag16S_EndOfBlock_Value));
			return new MT548_SequenceB(subBlock);
        }
    }
    
    /// <summary>
    /// Settlement Parties
    /// <summary>
    public partial class MT548_SequenceB1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "SETPRTY";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95C_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95L_Party { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public string Tag97A_Account { get; set; }
        /// <summary>
        /// Safekeeping Account
        /// <summary>
		public string Tag97B_Account { get; set; }
        /// <summary>
        /// Sender's Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "SETPRTY";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceB1()
        {
        }
        
        public MT548_SequenceB1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95C_Party != null)
				tags.AddRange(Tag95C_Party.Select(x => new SwiftTag("95C", x)).ToList());
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95L_Party != null)
				tags.AddRange(Tag95L_Party.Select(x => new SwiftTag("95L", x)).ToList());
			if (Tag97A_Account != null)
				tags.Add(new SwiftTag("97A", Tag97A_Account));
			if (Tag97B_Account != null)
				tags.Add(new SwiftTag("97B", Tag97B_Account));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95C") && (i <= 2))
				{
					if (Tag95C_Party == null)
						Tag95C_Party = new List<string>();
					Tag95C_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95L") && (i <= 2))
				{
					if (Tag95L_Party == null)
						Tag95L_Party = new List<string>();
					Tag95L_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "97A") && (i <= 3))
				{
					Tag97A_Account = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "97B") && (i <= 3))
				{
					Tag97B_Account = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "20C") && (i <= 4))
				{
					Tag20C_Reference = tag.Value;
					i = 4;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 5))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 5;
				}
			}
        }
        
        public static List<MT548_SequenceB1> GetMT548_SequenceB1List(SwiftTagList tags)
        {
			List<MT548_SequenceB1> result = new List<MT548_SequenceB1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT548_SequenceB1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceB1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT548_SequenceB1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceB1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT548_SequenceB1 sequence = new MT548_SequenceB1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Penalties
    /// <summary>
    public partial class MT548_SequenceC
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "PENA";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Statement Period
        /// <summary>
		public string Tag69A_Period { get; set; }
        /// <summary>
        /// Statement Period
        /// <summary>
		public string Tag69B_Period { get; set; }
        /// <summary>
        /// Complete/Updates Indicator
        /// <summary>
		public string Tag22F_Indicator { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95L_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Penalties per currency for a party
        /// <summary>
		public MT548_SequenceC1 SequenceC1 { get; set; }
        /// <summary>
        /// Additional Information Narrative
        /// <summary>
		public string Tag70E_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "PENA";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceC()
        {
        }
        
        public MT548_SequenceC(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag69A_Period != null)
				tags.Add(new SwiftTag("69A", Tag69A_Period));
			if (Tag69B_Period != null)
				tags.Add(new SwiftTag("69B", Tag69B_Period));
			if (Tag22F_Indicator != null)
				tags.Add(new SwiftTag("22F", Tag22F_Indicator));
			if (Tag95L_Party != null)
				tags.AddRange(Tag95L_Party.Select(x => new SwiftTag("95L", x)).ToList());
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (SequenceC1 != null)
				tags.AddRange(SequenceC1.GetTags());
			if (Tag70E_Narrative != null)
				tags.Add(new SwiftTag("70E", Tag70E_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "69A") && (i <= 2))
				{
					Tag69A_Period = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "69B") && (i <= 2))
				{
					Tag69B_Period = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "22F") && (i <= 3))
				{
					Tag22F_Indicator = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "95L") && (i <= 4))
				{
					if (Tag95L_Party == null)
						Tag95L_Party = new List<string>();
					Tag95L_Party.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "95P") && (i <= 4))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "70E") && (i <= 5))
				{
					Tag70E_Narrative = tag.Value;
					i = 5;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 6))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 6;
				}
			}
			SequenceC1 = MT548_SequenceC1.GetMT548_SequenceC1(tags);
        }
        
        public static MT548_SequenceC GetMT548_SequenceC(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT548_SequenceC.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC.Tag16S_EndOfBlock_Value));
			return new MT548_SequenceC(subBlock);
        }
    }
    
    /// <summary>
    /// Penalties per currency for a party
    /// <summary>
    public partial class MT548_SequenceC1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "PENACUR";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Currency Of Penalties
        /// <summary>
		public string Tag11A_CurrencyOfPenalties { get; set; }
        /// <summary>
        /// Computation Date/Time
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Computation Date/Time
        /// <summary>
		public string Tag98C_DateTime { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95L_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party Capacity Indicator
        /// <summary>
		public string Tag22F_Indicator { get; set; }
        /// <summary>
        /// Penalties per counter party
        /// <summary>
		public MT548_SequenceC1a SequenceC1a { get; set; }
        /// <summary>
        /// Additional Information Narrative
        /// <summary>
		public string Tag70E_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "PENACUR";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceC1()
        {
        }
        
        public MT548_SequenceC1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag11A_CurrencyOfPenalties != null)
				tags.Add(new SwiftTag("11A", Tag11A_CurrencyOfPenalties));
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98C_DateTime != null)
				tags.Add(new SwiftTag("98C", Tag98C_DateTime));
			if (Tag95L_Party != null)
				tags.AddRange(Tag95L_Party.Select(x => new SwiftTag("95L", x)).ToList());
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag22F_Indicator != null)
				tags.Add(new SwiftTag("22F", Tag22F_Indicator));
			if (SequenceC1a != null)
				tags.AddRange(SequenceC1a.GetTags());
			if (Tag70E_Narrative != null)
				tags.Add(new SwiftTag("70E", Tag70E_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "11A") && (i <= 2))
				{
					Tag11A_CurrencyOfPenalties = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "98A") && (i <= 3))
				{
					Tag98A_Date = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "98C") && (i <= 3))
				{
					Tag98C_DateTime = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "95L") && (i <= 4))
				{
					if (Tag95L_Party == null)
						Tag95L_Party = new List<string>();
					Tag95L_Party.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "95P") && (i <= 4))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "95Q") && (i <= 4))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "95R") && (i <= 4))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "22F") && (i <= 5))
				{
					Tag22F_Indicator = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "70E") && (i <= 6))
				{
					Tag70E_Narrative = tag.Value;
					i = 6;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 7))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 7;
				}
			}
			SequenceC1a = MT548_SequenceC1a.GetMT548_SequenceC1a(tags);
        }
        
        public static MT548_SequenceC1 GetMT548_SequenceC1(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT548_SequenceC1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1.Tag16S_EndOfBlock_Value));
			return new MT548_SequenceC1(subBlock);
        }
    }
    
    /// <summary>
    /// Penalties per counter party
    /// <summary>
    public partial class MT548_SequenceC1a
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "PENACOUNT";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95L_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party Capacity Indicator
        /// <summary>
		public string Tag22F_Indicator { get; set; }
        /// <summary>
        /// Bilateral Net Amount
        /// <summary>
		public string Tag19A_Amount { get; set; }
        /// <summary>
        /// Penalty Details
        /// <summary>
		public List<MT548_SequenceC1a1> SequenceC1a1List { get; set; }
        /// <summary>
        /// Additional Information Narrative
        /// <summary>
		public string Tag70E_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "PENACOUNT";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceC1a()
        {
        }
        
        public MT548_SequenceC1a(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95L_Party != null)
				tags.AddRange(Tag95L_Party.Select(x => new SwiftTag("95L", x)).ToList());
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag22F_Indicator != null)
				tags.Add(new SwiftTag("22F", Tag22F_Indicator));
			if (Tag19A_Amount != null)
				tags.Add(new SwiftTag("19A", Tag19A_Amount));
			if (SequenceC1a1List != null)
				tags.AddRange(SequenceC1a1List.SelectMany(x => x.GetTags()).ToList());
			if (Tag70E_Narrative != null)
				tags.Add(new SwiftTag("70E", Tag70E_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95L") && (i <= 2))
				{
					if (Tag95L_Party == null)
						Tag95L_Party = new List<string>();
					Tag95L_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "22F") && (i <= 3))
				{
					Tag22F_Indicator = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "19A") && (i <= 4))
				{
					Tag19A_Amount = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "70E") && (i <= 5))
				{
					Tag70E_Narrative = tag.Value;
					i = 5;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 6))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 6;
				}
			}
			SequenceC1a1List = MT548_SequenceC1a1.GetMT548_SequenceC1a1List(tags);
        }
        
        public static MT548_SequenceC1a GetMT548_SequenceC1a(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT548_SequenceC1a.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1a.Tag16S_EndOfBlock_Value));
			return new MT548_SequenceC1a(subBlock);
        }
    }
    
    /// <summary>
    /// Penalty Details
    /// <summary>
    public partial class MT548_SequenceC1a1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "PENDET";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public List<string> Tag20C_Reference { get; set; }
        /// <summary>
        /// Penalty Type Indicator
        /// <summary>
		public string Tag22F_Indicator { get; set; }
        /// <summary>
        /// Amount Computed Flag
        /// <summary>
		public string Tag17B_AmountComputedFlag { get; set; }
        /// <summary>
        /// Penalty Status
        /// <summary>
		public string Tag25D_Status { get; set; }
        /// <summary>
        /// Reason Code
        /// <summary>
		public List<string> Tag24B_ReasonCode { get; set; }
        /// <summary>
        /// Reason Narrative
        /// <summary>
		public string Tag70D_Narrative { get; set; }
        /// <summary>
        /// Amount Computed
        /// <summary>
		public string Tag19A_Amount { get; set; }
        /// <summary>
        /// Calculation Method Indicator
        /// <summary>
		public string Tag22F_CalculationMethodIndicator { get; set; }
        /// <summary>
        /// Number Days
        /// <summary>
		public string Tag99A_NumberDays { get; set; }
        /// <summary>
        /// Calculation Details
        /// <summary>
		public List<MT548_SequenceC1a1A> SequenceC1a1AList { get; set; }
        /// <summary>
        /// Additional Information Narrative
        /// <summary>
		public string Tag70E_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "PENDET";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceC1a1()
        {
        }
        
        public MT548_SequenceC1a1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag20C_Reference != null)
				tags.AddRange(Tag20C_Reference.Select(x => new SwiftTag("20C", x)).ToList());
			if (Tag22F_Indicator != null)
				tags.Add(new SwiftTag("22F", Tag22F_Indicator));
			if (Tag17B_AmountComputedFlag != null)
				tags.Add(new SwiftTag("17B", Tag17B_AmountComputedFlag));
			if (Tag25D_Status != null)
				tags.Add(new SwiftTag("25D", Tag25D_Status));
			if (Tag24B_ReasonCode != null)
				tags.AddRange(Tag24B_ReasonCode.Select(x => new SwiftTag("24B", x)).ToList());
			if (Tag70D_Narrative != null)
				tags.Add(new SwiftTag("70D", Tag70D_Narrative));
			if (Tag19A_Amount != null)
				tags.Add(new SwiftTag("19A", Tag19A_Amount));
			if (Tag22F_CalculationMethodIndicator != null)
				tags.Add(new SwiftTag("22F", Tag22F_CalculationMethodIndicator));
			if (Tag99A_NumberDays != null)
				tags.Add(new SwiftTag("99A", Tag99A_NumberDays));
			if (SequenceC1a1AList != null)
				tags.AddRange(SequenceC1a1AList.SelectMany(x => x.GetTags()).ToList());
			if (Tag70E_Narrative != null)
				tags.Add(new SwiftTag("70E", Tag70E_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "20C") && (i <= 2))
				{
					if (Tag20C_Reference == null)
						Tag20C_Reference = new List<string>();
					Tag20C_Reference.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "22F") && (i <= 3))
				{
					Tag22F_Indicator = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "17B") && (i <= 4))
				{
					Tag17B_AmountComputedFlag = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "25D") && (i <= 5))
				{
					Tag25D_Status = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "24B") && (i <= 6))
				{
					if (Tag24B_ReasonCode == null)
						Tag24B_ReasonCode = new List<string>();
					Tag24B_ReasonCode.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "70D") && (i <= 7))
				{
					Tag70D_Narrative = tag.Value;
					i = 7;
				}
				else if ((tag.Name == "19A") && (i <= 8))
				{
					Tag19A_Amount = tag.Value;
					i = 8;
				}
				else if ((tag.Name == "22F") && (i <= 9))
				{
					Tag22F_CalculationMethodIndicator = tag.Value;
					i = 9;
				}
				else if ((tag.Name == "99A") && (i <= 10))
				{
					Tag99A_NumberDays = tag.Value;
					i = 10;
				}
				else if ((tag.Name == "70E") && (i <= 11))
				{
					Tag70E_Narrative = tag.Value;
					i = 11;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 12))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 12;
				}
			}
			SequenceC1a1AList = MT548_SequenceC1a1A.GetMT548_SequenceC1a1AList(tags);
        }
        
        public static List<MT548_SequenceC1a1> GetMT548_SequenceC1a1List(SwiftTagList tags)
        {
			List<MT548_SequenceC1a1> result = new List<MT548_SequenceC1a1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT548_SequenceC1a1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1a1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT548_SequenceC1a1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1a1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT548_SequenceC1a1 sequence = new MT548_SequenceC1a1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Calculation Details
    /// <summary>
    public partial class MT548_SequenceC1a1A
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "CALDET";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Date/Time
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Date/Time
        /// <summary>
		public string Tag98C_DateTime { get; set; }
        /// <summary>
        /// Trade Date/Time
        /// <summary>
		public string Tag98E_DateTime { get; set; }
        /// <summary>
        /// Activity Flag
        /// <summary>
		public string Tag17B_MissingFlag { get; set; }
        /// <summary>
        /// Financial Instrument Attributes
        /// <summary>
		public MT548_SequenceC1a1A1 SequenceC1a1A1 { get; set; }
        /// <summary>
        /// Rate
        /// <summary>
		public List<string> Tag92A_Rate { get; set; }
        /// <summary>
        /// Rate
        /// <summary>
		public List<string> Tag92B_Rate { get; set; }
        /// <summary>
        /// Amount
        /// <summary>
		public List<string> Tag19A_Amount { get; set; }
        /// <summary>
        /// Related Transaction
        /// <summary>
		public MT548_SequenceC1a1A2 SequenceC1a1A2 { get; set; }
        /// <summary>
        /// Additional Information Narrative
        /// <summary>
		public string Tag70E_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "CALDET";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceC1a1A()
        {
        }
        
        public MT548_SequenceC1a1A(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98C_DateTime != null)
				tags.Add(new SwiftTag("98C", Tag98C_DateTime));
			if (Tag98E_DateTime != null)
				tags.Add(new SwiftTag("98E", Tag98E_DateTime));
			if (Tag17B_MissingFlag != null)
				tags.Add(new SwiftTag("17B", Tag17B_MissingFlag));
			if (SequenceC1a1A1 != null)
				tags.AddRange(SequenceC1a1A1.GetTags());
			if (Tag92A_Rate != null)
				tags.AddRange(Tag92A_Rate.Select(x => new SwiftTag("92A", x)).ToList());
			if (Tag92B_Rate != null)
				tags.AddRange(Tag92B_Rate.Select(x => new SwiftTag("92B", x)).ToList());
			if (Tag19A_Amount != null)
				tags.AddRange(Tag19A_Amount.Select(x => new SwiftTag("19A", x)).ToList());
			if (SequenceC1a1A2 != null)
				tags.AddRange(SequenceC1a1A2.GetTags());
			if (Tag70E_Narrative != null)
				tags.Add(new SwiftTag("70E", Tag70E_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "98A") && (i <= 2))
				{
					Tag98A_Date = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "98C") && (i <= 2))
				{
					Tag98C_DateTime = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "98E") && (i <= 2))
				{
					Tag98E_DateTime = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "17B") && (i <= 3))
				{
					Tag17B_MissingFlag = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "92A") && (i <= 4))
				{
					if (Tag92A_Rate == null)
						Tag92A_Rate = new List<string>();
					Tag92A_Rate.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "92B") && (i <= 4))
				{
					if (Tag92B_Rate == null)
						Tag92B_Rate = new List<string>();
					Tag92B_Rate.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "19A") && (i <= 5))
				{
					if (Tag19A_Amount == null)
						Tag19A_Amount = new List<string>();
					Tag19A_Amount.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "70E") && (i <= 6))
				{
					Tag70E_Narrative = tag.Value;
					i = 6;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 7))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 7;
				}
			}
			SequenceC1a1A1 = MT548_SequenceC1a1A1.GetMT548_SequenceC1a1A1(tags);
			SequenceC1a1A2 = MT548_SequenceC1a1A2.GetMT548_SequenceC1a1A2(tags);
        }
        
        public static List<MT548_SequenceC1a1A> GetMT548_SequenceC1a1AList(SwiftTagList tags)
        {
			List<MT548_SequenceC1a1A> result = new List<MT548_SequenceC1a1A>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT548_SequenceC1a1A.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1a1A.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT548_SequenceC1a1A.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1a1A.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT548_SequenceC1a1A sequence = new MT548_SequenceC1a1A(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Financial Instrument Attributes
    /// <summary>
    public partial class MT548_SequenceC1a1A1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "FIA";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Identification Of Financial Instrument
        /// <summary>
		public string Tag35B_IdentificationOfFinancialInstrument { get; set; }
        /// <summary>
        /// Type of Financial Instrument
        /// <summary>
		public string Tag12A_TypeOfFinancialInstrument { get; set; }
        /// <summary>
        /// Type of Financial Instrument
        /// <summary>
		public string Tag12C_TypeOfFinancialInstrument { get; set; }
        /// <summary>
        /// Liquidity Flag
        /// <summary>
		public List<string> Tag17B_Flag { get; set; }
        /// <summary>
        /// Price
        /// <summary>
		public string Tag90A_Price { get; set; }
        /// <summary>
        /// Price
        /// <summary>
		public string Tag90B_Price { get; set; }
        /// <summary>
        /// Source of Price
        /// <summary>
		public List<string> Tag94B_Place { get; set; }
        /// <summary>
        /// Place of Trade
        /// <summary>
		public List<string> Tag94L_Place { get; set; }
        /// <summary>
        /// Date/Time
        /// <summary>
		public List<string> Tag98A_Date { get; set; }
        /// <summary>
        /// Date/Time
        /// <summary>
		public List<string> Tag98C_DateTime { get; set; }
        /// <summary>
        /// Rate
        /// <summary>
		public List<string> Tag92A_Rate { get; set; }
        /// <summary>
        /// Exchange Rate
        /// <summary>
		public List<string> Tag92B_Rate { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public string Tag70E_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "FIA";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceC1a1A1()
        {
        }
        
        public MT548_SequenceC1a1A1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag35B_IdentificationOfFinancialInstrument != null)
				tags.Add(new SwiftTag("35B", Tag35B_IdentificationOfFinancialInstrument));
			if (Tag12A_TypeOfFinancialInstrument != null)
				tags.Add(new SwiftTag("12A", Tag12A_TypeOfFinancialInstrument));
			if (Tag12C_TypeOfFinancialInstrument != null)
				tags.Add(new SwiftTag("12C", Tag12C_TypeOfFinancialInstrument));
			if (Tag17B_Flag != null)
				tags.AddRange(Tag17B_Flag.Select(x => new SwiftTag("17B", x)).ToList());
			if (Tag90A_Price != null)
				tags.Add(new SwiftTag("90A", Tag90A_Price));
			if (Tag90B_Price != null)
				tags.Add(new SwiftTag("90B", Tag90B_Price));
			if (Tag94B_Place != null)
				tags.AddRange(Tag94B_Place.Select(x => new SwiftTag("94B", x)).ToList());
			if (Tag94L_Place != null)
				tags.AddRange(Tag94L_Place.Select(x => new SwiftTag("94L", x)).ToList());
			if (Tag98A_Date != null)
				tags.AddRange(Tag98A_Date.Select(x => new SwiftTag("98A", x)).ToList());
			if (Tag98C_DateTime != null)
				tags.AddRange(Tag98C_DateTime.Select(x => new SwiftTag("98C", x)).ToList());
			if (Tag92A_Rate != null)
				tags.AddRange(Tag92A_Rate.Select(x => new SwiftTag("92A", x)).ToList());
			if (Tag92B_Rate != null)
				tags.AddRange(Tag92B_Rate.Select(x => new SwiftTag("92B", x)).ToList());
			if (Tag70E_Narrative != null)
				tags.Add(new SwiftTag("70E", Tag70E_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "35B") && (i <= 2))
				{
					Tag35B_IdentificationOfFinancialInstrument = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "12A") && (i <= 3))
				{
					Tag12A_TypeOfFinancialInstrument = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "12C") && (i <= 3))
				{
					Tag12C_TypeOfFinancialInstrument = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "17B") && (i <= 4))
				{
					if (Tag17B_Flag == null)
						Tag17B_Flag = new List<string>();
					Tag17B_Flag.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "90A") && (i <= 5))
				{
					Tag90A_Price = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "90B") && (i <= 5))
				{
					Tag90B_Price = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "94B") && (i <= 6))
				{
					if (Tag94B_Place == null)
						Tag94B_Place = new List<string>();
					Tag94B_Place.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "94L") && (i <= 6))
				{
					if (Tag94L_Place == null)
						Tag94L_Place = new List<string>();
					Tag94L_Place.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "98A") && (i <= 7))
				{
					if (Tag98A_Date == null)
						Tag98A_Date = new List<string>();
					Tag98A_Date.Add(tag.Value);
					i = 7;
				}
				else if ((tag.Name == "98C") && (i <= 7))
				{
					if (Tag98C_DateTime == null)
						Tag98C_DateTime = new List<string>();
					Tag98C_DateTime.Add(tag.Value);
					i = 7;
				}
				else if ((tag.Name == "92A") && (i <= 8))
				{
					if (Tag92A_Rate == null)
						Tag92A_Rate = new List<string>();
					Tag92A_Rate.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "92B") && (i <= 8))
				{
					if (Tag92B_Rate == null)
						Tag92B_Rate = new List<string>();
					Tag92B_Rate.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "70E") && (i <= 9))
				{
					Tag70E_Narrative = tag.Value;
					i = 9;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 10))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 10;
				}
			}
        }
        
        public static MT548_SequenceC1a1A1 GetMT548_SequenceC1a1A1(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT548_SequenceC1a1A1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1a1A1.Tag16S_EndOfBlock_Value));
			return new MT548_SequenceC1a1A1(subBlock);
        }
    }
    
    /// <summary>
    /// Related Transaction
    /// <summary>
    public partial class MT548_SequenceC1a1A2
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "RELTRAN";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public List<string> Tag20C_Reference { get; set; }
        /// <summary>
        /// Transaction Details
        /// <summary>
		public MT548_SequenceC1a1A2a SequenceC1a1A2a { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "RELTRAN";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceC1a1A2()
        {
        }
        
        public MT548_SequenceC1a1A2(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag20C_Reference != null)
				tags.AddRange(Tag20C_Reference.Select(x => new SwiftTag("20C", x)).ToList());
			if (SequenceC1a1A2a != null)
				tags.AddRange(SequenceC1a1A2a.GetTags());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "20C") && (i <= 2))
				{
					if (Tag20C_Reference == null)
						Tag20C_Reference = new List<string>();
					Tag20C_Reference.Add(tag.Value);
					i = 2;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 3))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 3;
				}
			}
			SequenceC1a1A2a = MT548_SequenceC1a1A2a.GetMT548_SequenceC1a1A2a(tags);
        }
        
        public static MT548_SequenceC1a1A2 GetMT548_SequenceC1a1A2(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT548_SequenceC1a1A2.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1a1A2.Tag16S_EndOfBlock_Value));
			return new MT548_SequenceC1a1A2(subBlock);
        }
    }
    
    /// <summary>
    /// Transaction Details
    /// <summary>
    public partial class MT548_SequenceC1a1A2a
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "TRAN";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public string Tag22F_Indicator { get; set; }
        /// <summary>
        /// Date/Time
        /// <summary>
		public List<string> Tag98A_Date { get; set; }
        /// <summary>
        /// Date/Time
        /// <summary>
		public List<string> Tag98B_DateCode { get; set; }
        /// <summary>
        /// Date/Time
        /// <summary>
		public List<string> Tag98C_DateTime { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97A_Account { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97B_Account { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public List<string> Tag97E_Account { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95L_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22H_Indicator { get; set; }
        /// <summary>
        /// Posting Quantity
        /// <summary>
		public List<string> Tag36B_QuantityOfFinancialInstrument { get; set; }
        /// <summary>
        /// Posting Amount
        /// <summary>
		public string Tag19A_Amount { get; set; }
        /// <summary>
        /// Date/Time
        /// <summary>
		public List<string> Tag98C_Date { get; set; }
        /// <summary>
        /// Status
        /// <summary>
		public List<MT548_SequenceC1a1A2a1> SequenceC1a1A2a1List { get; set; }
        /// <summary>
        /// Additional Information Narrative
        /// <summary>
		public string Tag70E_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "TRAN";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceC1a1A2a()
        {
        }
        
        public MT548_SequenceC1a1A2a(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag22F_Indicator != null)
				tags.Add(new SwiftTag("22F", Tag22F_Indicator));
			if (Tag98A_Date != null)
				tags.AddRange(Tag98A_Date.Select(x => new SwiftTag("98A", x)).ToList());
			if (Tag98B_DateCode != null)
				tags.AddRange(Tag98B_DateCode.Select(x => new SwiftTag("98B", x)).ToList());
			if (Tag98C_DateTime != null)
				tags.AddRange(Tag98C_DateTime.Select(x => new SwiftTag("98C", x)).ToList());
			if (Tag97A_Account != null)
				tags.AddRange(Tag97A_Account.Select(x => new SwiftTag("97A", x)).ToList());
			if (Tag97B_Account != null)
				tags.AddRange(Tag97B_Account.Select(x => new SwiftTag("97B", x)).ToList());
			if (Tag97E_Account != null)
				tags.AddRange(Tag97E_Account.Select(x => new SwiftTag("97E", x)).ToList());
			if (Tag95L_Party != null)
				tags.AddRange(Tag95L_Party.Select(x => new SwiftTag("95L", x)).ToList());
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag22H_Indicator != null)
				tags.AddRange(Tag22H_Indicator.Select(x => new SwiftTag("22H", x)).ToList());
			if (Tag36B_QuantityOfFinancialInstrument != null)
				tags.AddRange(Tag36B_QuantityOfFinancialInstrument.Select(x => new SwiftTag("36B", x)).ToList());
			if (Tag19A_Amount != null)
				tags.Add(new SwiftTag("19A", Tag19A_Amount));
			if (Tag98C_Date != null)
				tags.AddRange(Tag98C_Date.Select(x => new SwiftTag("98C", x)).ToList());
			if (SequenceC1a1A2a1List != null)
				tags.AddRange(SequenceC1a1A2a1List.SelectMany(x => x.GetTags()).ToList());
			if (Tag70E_Narrative != null)
				tags.Add(new SwiftTag("70E", Tag70E_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "22F") && (i <= 2))
				{
					Tag22F_Indicator = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "98A") && (i <= 3))
				{
					if (Tag98A_Date == null)
						Tag98A_Date = new List<string>();
					Tag98A_Date.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "98B") && (i <= 3))
				{
					if (Tag98B_DateCode == null)
						Tag98B_DateCode = new List<string>();
					Tag98B_DateCode.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "98C") && (i <= 3))
				{
					if (Tag98C_DateTime == null)
						Tag98C_DateTime = new List<string>();
					Tag98C_DateTime.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "97A") && (i <= 4))
				{
					if (Tag97A_Account == null)
						Tag97A_Account = new List<string>();
					Tag97A_Account.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "97B") && (i <= 4))
				{
					if (Tag97B_Account == null)
						Tag97B_Account = new List<string>();
					Tag97B_Account.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "97E") && (i <= 4))
				{
					if (Tag97E_Account == null)
						Tag97E_Account = new List<string>();
					Tag97E_Account.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "95L") && (i <= 5))
				{
					if (Tag95L_Party == null)
						Tag95L_Party = new List<string>();
					Tag95L_Party.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "95P") && (i <= 5))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "95Q") && (i <= 5))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "95R") && (i <= 5))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "22H") && (i <= 6))
				{
					if (Tag22H_Indicator == null)
						Tag22H_Indicator = new List<string>();
					Tag22H_Indicator.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "36B") && (i <= 7))
				{
					if (Tag36B_QuantityOfFinancialInstrument == null)
						Tag36B_QuantityOfFinancialInstrument = new List<string>();
					Tag36B_QuantityOfFinancialInstrument.Add(tag.Value);
					i = 7;
				}
				else if ((tag.Name == "19A") && (i <= 8))
				{
					Tag19A_Amount = tag.Value;
					i = 8;
				}
				else if ((tag.Name == "98C") && (i <= 9))
				{
					if (Tag98C_Date == null)
						Tag98C_Date = new List<string>();
					Tag98C_Date.Add(tag.Value);
					i = 9;
				}
				else if ((tag.Name == "70E") && (i <= 10))
				{
					Tag70E_Narrative = tag.Value;
					i = 10;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 11))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 11;
				}
			}
			SequenceC1a1A2a1List = MT548_SequenceC1a1A2a1.GetMT548_SequenceC1a1A2a1List(tags);
        }
        
        public static MT548_SequenceC1a1A2a GetMT548_SequenceC1a1A2a(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT548_SequenceC1a1A2a.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1a1A2a.Tag16S_EndOfBlock_Value));
			return new MT548_SequenceC1a1A2a(subBlock);
        }
    }
    
    /// <summary>
    /// Status
    /// <summary>
    public partial class MT548_SequenceC1a1A2a1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "STAT";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Status
        /// <summary>
		public string Tag25D_Status { get; set; }
        /// <summary>
        /// Status
        /// <summary>
		public List<MT548_SequenceC1a1A2a1A> SequenceC1a1A2a1AList { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "STAT";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceC1a1A2a1()
        {
        }
        
        public MT548_SequenceC1a1A2a1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag25D_Status != null)
				tags.Add(new SwiftTag("25D", Tag25D_Status));
			if (SequenceC1a1A2a1AList != null)
				tags.AddRange(SequenceC1a1A2a1AList.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "25D") && (i <= 2))
				{
					Tag25D_Status = tag.Value;
					i = 2;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 3))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 3;
				}
			}
			SequenceC1a1A2a1AList = MT548_SequenceC1a1A2a1A.GetMT548_SequenceC1a1A2a1AList(tags);
        }
        
        public static List<MT548_SequenceC1a1A2a1> GetMT548_SequenceC1a1A2a1List(SwiftTagList tags)
        {
			List<MT548_SequenceC1a1A2a1> result = new List<MT548_SequenceC1a1A2a1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT548_SequenceC1a1A2a1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1a1A2a1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT548_SequenceC1a1A2a1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1a1A2a1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT548_SequenceC1a1A2a1 sequence = new MT548_SequenceC1a1A2a1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Status
    /// <summary>
    public partial class MT548_SequenceC1a1A2a1A
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "REAS";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Reason Code
        /// <summary>
		public string Tag24B_ReasonCode { get; set; }
        /// <summary>
        /// Reason Narrative
        /// <summary>
		public string Tag70D_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "REAS";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceC1a1A2a1A()
        {
        }
        
        public MT548_SequenceC1a1A2a1A(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag24B_ReasonCode != null)
				tags.Add(new SwiftTag("24B", Tag24B_ReasonCode));
			if (Tag70D_Narrative != null)
				tags.Add(new SwiftTag("70D", Tag70D_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "24B") && (i <= 2))
				{
					Tag24B_ReasonCode = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "70D") && (i <= 3))
				{
					Tag70D_Narrative = tag.Value;
					i = 3;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 4))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 4;
				}
			}
        }
        
        public static List<MT548_SequenceC1a1A2a1A> GetMT548_SequenceC1a1A2a1AList(SwiftTagList tags)
        {
			List<MT548_SequenceC1a1A2a1A> result = new List<MT548_SequenceC1a1A2a1A>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT548_SequenceC1a1A2a1A.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1a1A2a1A.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT548_SequenceC1a1A2a1A.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceC1a1A2a1A.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT548_SequenceC1a1A2a1A sequence = new MT548_SequenceC1a1A2a1A(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Additional Information
    /// <summary>
    public partial class MT548_SequenceD
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "ADDINFO";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95C_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95L_Party { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "ADDINFO";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT548_SequenceD()
        {
        }
        
        public MT548_SequenceD(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95C_Party != null)
				tags.AddRange(Tag95C_Party.Select(x => new SwiftTag("95C", x)).ToList());
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95L_Party != null)
				tags.AddRange(Tag95L_Party.Select(x => new SwiftTag("95L", x)).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95C") && (i <= 2))
				{
					if (Tag95C_Party == null)
						Tag95C_Party = new List<string>();
					Tag95C_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95L") && (i <= 2))
				{
					if (Tag95L_Party == null)
						Tag95L_Party = new List<string>();
					Tag95L_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 3))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 3;
				}
			}
        }
        
        public static List<MT548_SequenceD> GetMT548_SequenceDList(SwiftTagList tags)
        {
			List<MT548_SequenceD> result = new List<MT548_SequenceD>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT548_SequenceD.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceD.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT548_SequenceD.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT548_SequenceD.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT548_SequenceD sequence = new MT548_SequenceD(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
}
