//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swift.Net.Mt.Category5
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// MT558 (SRG 2019)
    /// <summary>
    public partial class MT558 : SwiftMessage
    {
        
		public override SwiftBlock4 Block4 { get => new SwiftBlock4(GetBlock4Tags()); set => SetBlock4Tags(value); }

        /// <summary>
        /// General Information
        /// <summary>
		public MT558_SequenceA SequenceA { get; set; }
        /// <summary>
        /// Deal Transaction Details
        /// <summary>
		public MT558_SequenceB SequenceB { get; set; }
        /// <summary>
        /// Securities Movement
        /// <summary>
		public List<MT558_SequenceC> SequenceCList { get; set; }
        /// <summary>
        /// Cash Movement
        /// <summary>
		public List<MT558_SequenceD> SequenceDList { get; set; }
        /// <summary>
        /// Additional Information
        /// <summary>
		public MT558_SequenceE SequenceE { get; set; }
        
        public MT558()
        {
        }
        
        public MT558(SwiftTagList tags)
        {
			SetBlock4Tags(tags);
        }
        
        public virtual SwiftTagList GetBlock4Tags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (SequenceA != null)
				tags.AddRange(SequenceA.GetTags());
			if (SequenceB != null)
				tags.AddRange(SequenceB.GetTags());
			if (SequenceCList != null)
				tags.AddRange(SequenceCList.SelectMany(x => x.GetTags()).ToList());
			if (SequenceDList != null)
				tags.AddRange(SequenceDList.SelectMany(x => x.GetTags()).ToList());
			if (SequenceE != null)
				tags.AddRange(SequenceE.GetTags());
			return tags;
        }
        
        public virtual void SetBlock4Tags(SwiftTagList tags)
        {
			SequenceA = MT558_SequenceA.GetMT558_SequenceA(tags);
			SequenceB = MT558_SequenceB.GetMT558_SequenceB(tags);
			SequenceCList = MT558_SequenceC.GetMT558_SequenceCList(tags);
			SequenceDList = MT558_SequenceD.GetMT558_SequenceDList(tags);
			SequenceE = MT558_SequenceE.GetMT558_SequenceE(tags);
        }
        
        public static MT558 Parse(string message)
        {
			SwiftMessage swiftMessage = new SwiftParser().GetSwiftMessage(message);
			MT558 result = new MT558()
			{
				Block1 = swiftMessage.Block1,
				Block2 = swiftMessage.Block2,
				Block3 = swiftMessage.Block3,
				Block4 = swiftMessage.Block4,
				Block5 = swiftMessage.Block5,
			};
			return result;
        }
        
        public static string Write(MT558 message)
        {
			return new SwiftWriter().GetFinMessage(message);
        }
    }
    
    /// <summary>
    /// General Information
    /// <summary>
    public partial class MT558_SequenceA
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "GENL";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Page Number/Continuation Indicator
        /// <summary>
		public string Tag28E_PageNumberContinuationIndicator { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public List<string> Tag20C_Reference { get; set; }
        /// <summary>
        /// Function Of The Message
        /// <summary>
		public string Tag23G_FunctionOfTheMessage { get; set; }
        /// <summary>
        /// Date/Time
        /// <summary>
		public List<string> Tag98A_Date { get; set; }
        /// <summary>
        /// Date/Time
        /// <summary>
		public List<string> Tag98C_DateTime { get; set; }
        /// <summary>
        /// Preparation Date/Time
        /// <summary>
		public List<string> Tag98E_DateTime { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22H_Indicator { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Number Identification
        /// <summary>
		public List<string> Tag13B_NumberIdentification { get; set; }
        /// <summary>
        /// Collateral Parties
        /// <summary>
		public List<MT558_SequenceA1> SequenceA1List { get; set; }
        /// <summary>
        /// Status
        /// <summary>
		public List<MT558_SequenceA2> SequenceA2List { get; set; }
        /// <summary>
        /// Flag
        /// <summary>
		public List<string> Tag17B_Flag { get; set; }
        /// <summary>
        /// Required Margin Amount
        /// <summary>
		public List<string> Tag19A_Amount { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public List<string> Tag70D_Narrative { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public List<string> Tag70E_Narrative { get; set; }
        /// <summary>
        /// Linkages
        /// <summary>
		public List<MT558_SequenceA3> SequenceA3List { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "GENL";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT558_SequenceA()
        {
        }
        
        public MT558_SequenceA(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag28E_PageNumberContinuationIndicator != null)
				tags.Add(new SwiftTag("28E", Tag28E_PageNumberContinuationIndicator));
			if (Tag20C_Reference != null)
				tags.AddRange(Tag20C_Reference.Select(x => new SwiftTag("20C", x)).ToList());
			if (Tag23G_FunctionOfTheMessage != null)
				tags.Add(new SwiftTag("23G", Tag23G_FunctionOfTheMessage));
			if (Tag98A_Date != null)
				tags.AddRange(Tag98A_Date.Select(x => new SwiftTag("98A", x)).ToList());
			if (Tag98C_DateTime != null)
				tags.AddRange(Tag98C_DateTime.Select(x => new SwiftTag("98C", x)).ToList());
			if (Tag98E_DateTime != null)
				tags.AddRange(Tag98E_DateTime.Select(x => new SwiftTag("98E", x)).ToList());
			if (Tag22H_Indicator != null)
				tags.AddRange(Tag22H_Indicator.Select(x => new SwiftTag("22H", x)).ToList());
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (Tag13B_NumberIdentification != null)
				tags.AddRange(Tag13B_NumberIdentification.Select(x => new SwiftTag("13B", x)).ToList());
			if (SequenceA1List != null)
				tags.AddRange(SequenceA1List.SelectMany(x => x.GetTags()).ToList());
			if (SequenceA2List != null)
				tags.AddRange(SequenceA2List.SelectMany(x => x.GetTags()).ToList());
			if (Tag17B_Flag != null)
				tags.AddRange(Tag17B_Flag.Select(x => new SwiftTag("17B", x)).ToList());
			if (Tag19A_Amount != null)
				tags.AddRange(Tag19A_Amount.Select(x => new SwiftTag("19A", x)).ToList());
			if (Tag70D_Narrative != null)
				tags.AddRange(Tag70D_Narrative.Select(x => new SwiftTag("70D", x)).ToList());
			if (Tag70E_Narrative != null)
				tags.AddRange(Tag70E_Narrative.Select(x => new SwiftTag("70E", x)).ToList());
			if (SequenceA3List != null)
				tags.AddRange(SequenceA3List.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "28E") && (i <= 2))
				{
					Tag28E_PageNumberContinuationIndicator = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "20C") && (i <= 3))
				{
					if (Tag20C_Reference == null)
						Tag20C_Reference = new List<string>();
					Tag20C_Reference.Add(tag.Value);
					i = 3;
				}
				else if ((tag.Name == "23G") && (i <= 4))
				{
					Tag23G_FunctionOfTheMessage = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "98A") && (i <= 5))
				{
					if (Tag98A_Date == null)
						Tag98A_Date = new List<string>();
					Tag98A_Date.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "98C") && (i <= 5))
				{
					if (Tag98C_DateTime == null)
						Tag98C_DateTime = new List<string>();
					Tag98C_DateTime.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "98E") && (i <= 5))
				{
					if (Tag98E_DateTime == null)
						Tag98E_DateTime = new List<string>();
					Tag98E_DateTime.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "22H") && (i <= 6))
				{
					if (Tag22H_Indicator == null)
						Tag22H_Indicator = new List<string>();
					Tag22H_Indicator.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "22F") && (i <= 6))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "13B") && (i <= 7))
				{
					if (Tag13B_NumberIdentification == null)
						Tag13B_NumberIdentification = new List<string>();
					Tag13B_NumberIdentification.Add(tag.Value);
					i = 7;
				}
				else if ((tag.Name == "17B") && (i <= 8))
				{
					if (Tag17B_Flag == null)
						Tag17B_Flag = new List<string>();
					Tag17B_Flag.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "19A") && (i <= 9))
				{
					if (Tag19A_Amount == null)
						Tag19A_Amount = new List<string>();
					Tag19A_Amount.Add(tag.Value);
					i = 9;
				}
				else if ((tag.Name == "70D") && (i <= 10))
				{
					if (Tag70D_Narrative == null)
						Tag70D_Narrative = new List<string>();
					Tag70D_Narrative.Add(tag.Value);
					i = 10;
				}
				else if ((tag.Name == "70E") && (i <= 10))
				{
					if (Tag70E_Narrative == null)
						Tag70E_Narrative = new List<string>();
					Tag70E_Narrative.Add(tag.Value);
					i = 10;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 11))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 11;
				}
			}
			SequenceA1List = MT558_SequenceA1.GetMT558_SequenceA1List(tags);
			SequenceA2List = MT558_SequenceA2.GetMT558_SequenceA2List(tags);
			SequenceA3List = MT558_SequenceA3.GetMT558_SequenceA3List(tags);
        }
        
        public static MT558_SequenceA GetMT558_SequenceA(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT558_SequenceA.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceA.Tag16S_EndOfBlock_Value));
			return new MT558_SequenceA(subBlock);
        }
    }
    
    /// <summary>
    /// Collateral Parties
    /// <summary>
    public partial class MT558_SequenceA1
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "COLLPRTY";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public string Tag97A_Account { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public string Tag97B_Account { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "COLLPRTY";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT558_SequenceA1()
        {
        }
        
        public MT558_SequenceA1(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag97A_Account != null)
				tags.Add(new SwiftTag("97A", Tag97A_Account));
			if (Tag97B_Account != null)
				tags.Add(new SwiftTag("97B", Tag97B_Account));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "97A") && (i <= 3))
				{
					Tag97A_Account = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "97B") && (i <= 3))
				{
					Tag97B_Account = tag.Value;
					i = 3;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 4))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 4;
				}
			}
        }
        
        public static List<MT558_SequenceA1> GetMT558_SequenceA1List(SwiftTagList tags)
        {
			List<MT558_SequenceA1> result = new List<MT558_SequenceA1>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT558_SequenceA1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceA1.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT558_SequenceA1.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceA1.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT558_SequenceA1 sequence = new MT558_SequenceA1(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Status
    /// <summary>
    public partial class MT558_SequenceA2
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "STAT";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Status
        /// <summary>
		public string Tag25D_Status { get; set; }
        /// <summary>
        /// Reason
        /// <summary>
		public List<MT558_SequenceA2a> SequenceA2aList { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "STAT";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT558_SequenceA2()
        {
        }
        
        public MT558_SequenceA2(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag25D_Status != null)
				tags.Add(new SwiftTag("25D", Tag25D_Status));
			if (SequenceA2aList != null)
				tags.AddRange(SequenceA2aList.SelectMany(x => x.GetTags()).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "25D") && (i <= 2))
				{
					Tag25D_Status = tag.Value;
					i = 2;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 3))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 3;
				}
			}
			SequenceA2aList = MT558_SequenceA2a.GetMT558_SequenceA2aList(tags);
        }
        
        public static List<MT558_SequenceA2> GetMT558_SequenceA2List(SwiftTagList tags)
        {
			List<MT558_SequenceA2> result = new List<MT558_SequenceA2>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT558_SequenceA2.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceA2.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT558_SequenceA2.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceA2.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT558_SequenceA2 sequence = new MT558_SequenceA2(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Reason
    /// <summary>
    public partial class MT558_SequenceA2a
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "REAS";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Reason
        /// <summary>
		public string Tag24B_Reason { get; set; }
        /// <summary>
        /// Reason Narrative
        /// <summary>
		public string Tag70D_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "REAS";
        /// <summary>
        /// End Of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT558_SequenceA2a()
        {
        }
        
        public MT558_SequenceA2a(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag24B_Reason != null)
				tags.Add(new SwiftTag("24B", Tag24B_Reason));
			if (Tag70D_Narrative != null)
				tags.Add(new SwiftTag("70D", Tag70D_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "24B") && (i <= 2))
				{
					Tag24B_Reason = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "70D") && (i <= 3))
				{
					Tag70D_Narrative = tag.Value;
					i = 3;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 4))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 4;
				}
			}
        }
        
        public static List<MT558_SequenceA2a> GetMT558_SequenceA2aList(SwiftTagList tags)
        {
			List<MT558_SequenceA2a> result = new List<MT558_SequenceA2a>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT558_SequenceA2a.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceA2a.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT558_SequenceA2a.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceA2a.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT558_SequenceA2a sequence = new MT558_SequenceA2a(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Linkages
    /// <summary>
    public partial class MT558_SequenceA3
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "LINK";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Linked Message
        /// <summary>
		public string Tag13A_NumberIdentification { get; set; }
        /// <summary>
        /// Linked Message
        /// <summary>
		public string Tag13B_NumberIdentification { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public string Tag20C_Reference { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "LINK";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT558_SequenceA3()
        {
        }
        
        public MT558_SequenceA3(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag13A_NumberIdentification != null)
				tags.Add(new SwiftTag("13A", Tag13A_NumberIdentification));
			if (Tag13B_NumberIdentification != null)
				tags.Add(new SwiftTag("13B", Tag13B_NumberIdentification));
			if (Tag20C_Reference != null)
				tags.Add(new SwiftTag("20C", Tag20C_Reference));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "13A") && (i <= 2))
				{
					Tag13A_NumberIdentification = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "13B") && (i <= 2))
				{
					Tag13B_NumberIdentification = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "20C") && (i <= 3))
				{
					Tag20C_Reference = tag.Value;
					i = 3;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 4))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 4;
				}
			}
        }
        
        public static List<MT558_SequenceA3> GetMT558_SequenceA3List(SwiftTagList tags)
        {
			List<MT558_SequenceA3> result = new List<MT558_SequenceA3>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT558_SequenceA3.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceA3.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT558_SequenceA3.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceA3.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT558_SequenceA3 sequence = new MT558_SequenceA3(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Deal Transaction Details
    /// <summary>
    public partial class MT558_SequenceB
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "DEALTRAN";
        /// <summary>
        /// Start Of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Number Count
        /// <summary>
		public string Tag99B_NumberCount { get; set; }
        /// <summary>
        /// Closing Date/Time
        /// <summary>
		public string Tag98A_Date { get; set; }
        /// <summary>
        /// Closing Date/Time
        /// <summary>
		public string Tag98B_DateCode { get; set; }
        /// <summary>
        /// Closing Date/Time
        /// <summary>
		public string Tag98C_DateTime { get; set; }
        /// <summary>
        /// Amount
        /// <summary>
		public List<string> Tag19A_Amount { get; set; }
        /// <summary>
        /// Rate
        /// <summary>
		public List<string> Tag92A_Rate { get; set; }
        /// <summary>
        /// Rate
        /// <summary>
		public List<string> Tag92C_Rate { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22F_Indicator { get; set; }
        /// <summary>
        /// Indicator
        /// <summary>
		public List<string> Tag22H_Indicator { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "DEALTRAN";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT558_SequenceB()
        {
        }
        
        public MT558_SequenceB(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag99B_NumberCount != null)
				tags.Add(new SwiftTag("99B", Tag99B_NumberCount));
			if (Tag98A_Date != null)
				tags.Add(new SwiftTag("98A", Tag98A_Date));
			if (Tag98B_DateCode != null)
				tags.Add(new SwiftTag("98B", Tag98B_DateCode));
			if (Tag98C_DateTime != null)
				tags.Add(new SwiftTag("98C", Tag98C_DateTime));
			if (Tag19A_Amount != null)
				tags.AddRange(Tag19A_Amount.Select(x => new SwiftTag("19A", x)).ToList());
			if (Tag92A_Rate != null)
				tags.AddRange(Tag92A_Rate.Select(x => new SwiftTag("92A", x)).ToList());
			if (Tag92C_Rate != null)
				tags.AddRange(Tag92C_Rate.Select(x => new SwiftTag("92C", x)).ToList());
			if (Tag22F_Indicator != null)
				tags.AddRange(Tag22F_Indicator.Select(x => new SwiftTag("22F", x)).ToList());
			if (Tag22H_Indicator != null)
				tags.AddRange(Tag22H_Indicator.Select(x => new SwiftTag("22H", x)).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "99B") && (i <= 2))
				{
					Tag99B_NumberCount = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "98A") && (i <= 3))
				{
					Tag98A_Date = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "98B") && (i <= 3))
				{
					Tag98B_DateCode = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "98C") && (i <= 3))
				{
					Tag98C_DateTime = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "19A") && (i <= 4))
				{
					if (Tag19A_Amount == null)
						Tag19A_Amount = new List<string>();
					Tag19A_Amount.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "92A") && (i <= 5))
				{
					if (Tag92A_Rate == null)
						Tag92A_Rate = new List<string>();
					Tag92A_Rate.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "92C") && (i <= 5))
				{
					if (Tag92C_Rate == null)
						Tag92C_Rate = new List<string>();
					Tag92C_Rate.Add(tag.Value);
					i = 5;
				}
				else if ((tag.Name == "22F") && (i <= 6))
				{
					if (Tag22F_Indicator == null)
						Tag22F_Indicator = new List<string>();
					Tag22F_Indicator.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "22H") && (i <= 6))
				{
					if (Tag22H_Indicator == null)
						Tag22H_Indicator = new List<string>();
					Tag22H_Indicator.Add(tag.Value);
					i = 6;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 7))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 7;
				}
			}
        }
        
        public static MT558_SequenceB GetMT558_SequenceB(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT558_SequenceB.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceB.Tag16S_EndOfBlock_Value));
			return new MT558_SequenceB(subBlock);
        }
    }
    
    /// <summary>
    /// Securities Movement
    /// <summary>
    public partial class MT558_SequenceC
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "SECMOVE";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// In/Out Indicator
        /// <summary>
		public string Tag22H_Indicator { get; set; }
        /// <summary>
        /// Identification Of Financial Instrument
        /// <summary>
		public string Tag35B_IdentificationOfFinancialInstrument { get; set; }
        /// <summary>
        /// Quantity of Securities
        /// <summary>
		public string Tag36B_QuantityOfFinancialInstrument { get; set; }
        /// <summary>
        /// Movement Status
        /// <summary>
		public string Tag25D_Status { get; set; }
        /// <summary>
        /// Flag
        /// <summary>
		public List<string> Tag17B_Flag { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public string Tag97A_Account { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public string Tag97B_Account { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public List<string> Tag20C_Reference { get; set; }
        /// <summary>
        /// Amount: Margined Value Amount
        /// <summary>
		public string Tag19A_Amount { get; set; }
        /// <summary>
        /// Reason Narrative
        /// <summary>
		public string Tag70D_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "SECMOVE";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT558_SequenceC()
        {
        }
        
        public MT558_SequenceC(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag22H_Indicator != null)
				tags.Add(new SwiftTag("22H", Tag22H_Indicator));
			if (Tag35B_IdentificationOfFinancialInstrument != null)
				tags.Add(new SwiftTag("35B", Tag35B_IdentificationOfFinancialInstrument));
			if (Tag36B_QuantityOfFinancialInstrument != null)
				tags.Add(new SwiftTag("36B", Tag36B_QuantityOfFinancialInstrument));
			if (Tag25D_Status != null)
				tags.Add(new SwiftTag("25D", Tag25D_Status));
			if (Tag17B_Flag != null)
				tags.AddRange(Tag17B_Flag.Select(x => new SwiftTag("17B", x)).ToList());
			if (Tag97A_Account != null)
				tags.Add(new SwiftTag("97A", Tag97A_Account));
			if (Tag97B_Account != null)
				tags.Add(new SwiftTag("97B", Tag97B_Account));
			if (Tag20C_Reference != null)
				tags.AddRange(Tag20C_Reference.Select(x => new SwiftTag("20C", x)).ToList());
			if (Tag19A_Amount != null)
				tags.Add(new SwiftTag("19A", Tag19A_Amount));
			if (Tag70D_Narrative != null)
				tags.Add(new SwiftTag("70D", Tag70D_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "22H") && (i <= 2))
				{
					Tag22H_Indicator = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "35B") && (i <= 3))
				{
					Tag35B_IdentificationOfFinancialInstrument = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "36B") && (i <= 4))
				{
					Tag36B_QuantityOfFinancialInstrument = tag.Value;
					i = 4;
				}
				else if ((tag.Name == "25D") && (i <= 5))
				{
					Tag25D_Status = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "17B") && (i <= 6))
				{
					if (Tag17B_Flag == null)
						Tag17B_Flag = new List<string>();
					Tag17B_Flag.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "97A") && (i <= 7))
				{
					Tag97A_Account = tag.Value;
					i = 7;
				}
				else if ((tag.Name == "97B") && (i <= 7))
				{
					Tag97B_Account = tag.Value;
					i = 7;
				}
				else if ((tag.Name == "20C") && (i <= 8))
				{
					if (Tag20C_Reference == null)
						Tag20C_Reference = new List<string>();
					Tag20C_Reference.Add(tag.Value);
					i = 8;
				}
				else if ((tag.Name == "19A") && (i <= 9))
				{
					Tag19A_Amount = tag.Value;
					i = 9;
				}
				else if ((tag.Name == "70D") && (i <= 10))
				{
					Tag70D_Narrative = tag.Value;
					i = 10;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 11))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 11;
				}
			}
        }
        
        public static List<MT558_SequenceC> GetMT558_SequenceCList(SwiftTagList tags)
        {
			List<MT558_SequenceC> result = new List<MT558_SequenceC>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT558_SequenceC.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceC.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT558_SequenceC.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceC.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT558_SequenceC sequence = new MT558_SequenceC(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Cash Movement
    /// <summary>
    public partial class MT558_SequenceD
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "CASHMOVE";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// In/Out Indicator
        /// <summary>
		public string Tag22H_Indicator { get; set; }
        /// <summary>
        /// Cash Amount
        /// <summary>
		public string Tag19A_Amount { get; set; }
        /// <summary>
        /// Reference
        /// <summary>
		public List<string> Tag20C_Reference { get; set; }
        /// <summary>
        /// Movement Status
        /// <summary>
		public string Tag25D_Status { get; set; }
        /// <summary>
        /// Flag
        /// <summary>
		public List<string> Tag17B_Flag { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public string Tag97A_Account { get; set; }
        /// <summary>
        /// Account
        /// <summary>
		public string Tag97E_Account { get; set; }
        /// <summary>
        /// Reason Narrative
        /// <summary>
		public string Tag70D_Narrative { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "CASHMOVE";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT558_SequenceD()
        {
        }
        
        public MT558_SequenceD(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag22H_Indicator != null)
				tags.Add(new SwiftTag("22H", Tag22H_Indicator));
			if (Tag19A_Amount != null)
				tags.Add(new SwiftTag("19A", Tag19A_Amount));
			if (Tag20C_Reference != null)
				tags.AddRange(Tag20C_Reference.Select(x => new SwiftTag("20C", x)).ToList());
			if (Tag25D_Status != null)
				tags.Add(new SwiftTag("25D", Tag25D_Status));
			if (Tag17B_Flag != null)
				tags.AddRange(Tag17B_Flag.Select(x => new SwiftTag("17B", x)).ToList());
			if (Tag97A_Account != null)
				tags.Add(new SwiftTag("97A", Tag97A_Account));
			if (Tag97E_Account != null)
				tags.Add(new SwiftTag("97E", Tag97E_Account));
			if (Tag70D_Narrative != null)
				tags.Add(new SwiftTag("70D", Tag70D_Narrative));
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "22H") && (i <= 2))
				{
					Tag22H_Indicator = tag.Value;
					i = 2;
				}
				else if ((tag.Name == "19A") && (i <= 3))
				{
					Tag19A_Amount = tag.Value;
					i = 3;
				}
				else if ((tag.Name == "20C") && (i <= 4))
				{
					if (Tag20C_Reference == null)
						Tag20C_Reference = new List<string>();
					Tag20C_Reference.Add(tag.Value);
					i = 4;
				}
				else if ((tag.Name == "25D") && (i <= 5))
				{
					Tag25D_Status = tag.Value;
					i = 5;
				}
				else if ((tag.Name == "17B") && (i <= 6))
				{
					if (Tag17B_Flag == null)
						Tag17B_Flag = new List<string>();
					Tag17B_Flag.Add(tag.Value);
					i = 6;
				}
				else if ((tag.Name == "97A") && (i <= 7))
				{
					Tag97A_Account = tag.Value;
					i = 7;
				}
				else if ((tag.Name == "97E") && (i <= 7))
				{
					Tag97E_Account = tag.Value;
					i = 7;
				}
				else if ((tag.Name == "70D") && (i <= 8))
				{
					Tag70D_Narrative = tag.Value;
					i = 8;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 9))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 9;
				}
			}
        }
        
        public static List<MT558_SequenceD> GetMT558_SequenceDList(SwiftTagList tags)
        {
			List<MT558_SequenceD> result = new List<MT558_SequenceD>();
			List<SwiftTagList> subBlocks = tags.GetSubBlocks(new SwiftTag("16R", MT558_SequenceD.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceD.Tag16S_EndOfBlock_Value));
			foreach(var subBlock in subBlocks)
			{
				var subTags = subBlock.GetSubBlock(new SwiftTag("16R", MT558_SequenceD.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceD.Tag16S_EndOfBlock_Value));
				if (subTags.Count == 0) continue;
				MT558_SequenceD sequence = new MT558_SequenceD(subTags);
				result.Add(sequence);
			}
			return result;
        }
    }
    
    /// <summary>
    /// Additional Information
    /// <summary>
    public partial class MT558_SequenceE
    {
        
		public static readonly string Tag16R_StartOfBlock_Value = "ADDINFO";
        /// <summary>
        /// Start of Block
        /// <summary>
		public string Tag16R_StartOfBlock { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95P_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95R_Party { get; set; }
        /// <summary>
        /// Party
        /// <summary>
		public List<string> Tag95Q_Party { get; set; }
		public static readonly string Tag16S_EndOfBlock_Value = "ADDINFO";
        /// <summary>
        /// End of Block
        /// <summary>
		public string Tag16S_EndOfBlock { get; set; }
        
        public MT558_SequenceE()
        {
        }
        
        public MT558_SequenceE(SwiftTagList tags)
        {
			SetTags(tags);
        }
        
        public virtual SwiftTagList GetTags()
        {
			SwiftTagList tags = new SwiftTagList();
			if (Tag16R_StartOfBlock != null)
				tags.Add(new SwiftTag("16R", Tag16R_StartOfBlock));
			if (Tag95P_Party != null)
				tags.AddRange(Tag95P_Party.Select(x => new SwiftTag("95P", x)).ToList());
			if (Tag95R_Party != null)
				tags.AddRange(Tag95R_Party.Select(x => new SwiftTag("95R", x)).ToList());
			if (Tag95Q_Party != null)
				tags.AddRange(Tag95Q_Party.Select(x => new SwiftTag("95Q", x)).ToList());
			if (Tag16S_EndOfBlock != null)
				tags.Add(new SwiftTag("16S", Tag16S_EndOfBlock));
			return tags;
        }
        
        public virtual void SetTags(SwiftTagList tags)
        {
			int i = 0;
			foreach(SwiftTag tag in tags)
			{
				if ((tag == new SwiftTag("16R", Tag16R_StartOfBlock_Value)) && (i <= 1))
				{
					Tag16R_StartOfBlock = tag.Value;
					i = 1;
				}
				else if ((tag.Name == "95P") && (i <= 2))
				{
					if (Tag95P_Party == null)
						Tag95P_Party = new List<string>();
					Tag95P_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95R") && (i <= 2))
				{
					if (Tag95R_Party == null)
						Tag95R_Party = new List<string>();
					Tag95R_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag.Name == "95Q") && (i <= 2))
				{
					if (Tag95Q_Party == null)
						Tag95Q_Party = new List<string>();
					Tag95Q_Party.Add(tag.Value);
					i = 2;
				}
				else if ((tag == new SwiftTag("16S", Tag16S_EndOfBlock_Value)) && (i <= 3))
				{
					Tag16S_EndOfBlock = tag.Value;
					i = 3;
				}
			}
        }
        
        public static MT558_SequenceE GetMT558_SequenceE(SwiftTagList tags)
        {
			SwiftTagList subBlock = tags.GetSubBlock(new SwiftTag("16R", MT558_SequenceE.Tag16R_StartOfBlock_Value), new SwiftTag("16S", MT558_SequenceE.Tag16S_EndOfBlock_Value));
			return new MT558_SequenceE(subBlock);
        }
    }
}
