//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swift.Net.Mt.Category5
{
    using System;
    using System.Collections.Generic;
    using System.Linq;


    /// <summary>
    /// MT599 (SRG 2019)
    /// <summary>
    public partial class MT599 : SwiftMessage
    {

        public override SwiftBlock4 Block4 { get => new SwiftBlock4(GetBlock4Tags()); set => SetBlock4Tags(value); }

        /// <summary>
        /// Transaction Reference Number
        /// <summary>
		public string Tag20_TransactionReferenceNumber { get; set; }
        /// <summary>
        /// Related Reference
        /// <summary>
		public string Tag21_RelatedReference { get; set; }
        /// <summary>
        /// Narrative
        /// <summary>
		public string Tag79_Narrative { get; set; }

        public MT599()
        {
        }

        public MT599(SwiftTagList tags)
        {
            SetBlock4Tags(tags);
        }

        public virtual SwiftTagList GetBlock4Tags()
        {
            SwiftTagList tags = new SwiftTagList();
            if (Tag20_TransactionReferenceNumber != null)
                tags.Add(new SwiftTag("20", Tag20_TransactionReferenceNumber));
            if (Tag21_RelatedReference != null)
                tags.Add(new SwiftTag("21", Tag21_RelatedReference));
            if (Tag79_Narrative != null)
                tags.Add(new SwiftTag("79", Tag79_Narrative));
            return tags;
        }

        public virtual void SetBlock4Tags(SwiftTagList tags)
        {
            int i = 0;
            foreach (SwiftTag tag in tags)
            {
                if ((tag.Name == "20") && (i <= 1))
                {
                    Tag20_TransactionReferenceNumber = tag.Value;
                    i = 1;
                }
                else if ((tag.Name == "21") && (i <= 2))
                {
                    Tag21_RelatedReference = tag.Value;
                    i = 2;
                }
                else if ((tag.Name == "79") && (i <= 3))
                {
                    Tag79_Narrative = tag.Value;
                    i = 3;
                }
            }
        }

        public static MT599 Parse(string message)
        {
            SwiftMessage swiftMessage = new SwiftParser().GetSwiftMessage(message);
            MT599 result = new MT599()
            {
                Block1 = swiftMessage.Block1,
                Block2 = swiftMessage.Block2,
                Block3 = swiftMessage.Block3,
                Block4 = swiftMessage.Block4,
                Block5 = swiftMessage.Block5,
            };
            return result;
        }

        public static string Write(MT599 message)
        {
            return new SwiftWriter().GetFinMessage(message);
        }
    }
}
